library(magrittr)
library(tidyverse)
library(feather)
library(tidycensus)
library(tigris)
library(ggplot2)
library(sf)
library(sp)
library(geofacet)
library(ggpubr)
library(ggh4x)
library(waffle)
library(hrbrthemes)

golds <- c("#ffc629", "#ffd664c7")
greys <- c("#b0b3b2", "#ced0d0")
golds2 <- c("#ffc629", "#ffda76", "#ffe397", "#fff2ce")
greys2 <- c("#b0b3b2", "#b1b1b1", "#cccccc", "#e2e2e2")

on_brand_Palette <- c("#ffc629","#b0b3b2","#9c5555","#7e6f9e","#52949a")

# R program for getting missing values
see_missing <- function(df) {
    as_tibble(lapply(df, function(x) sum(!is.na(x)))) %>%
            pivot_longer(cols = everything(),
                         names_to = "Variable", values_to = "Count")
                            }

fip_pth <- "data/state_fp_codes.csv" # nolint
st_fp <- read_csv(fip_pth)

desired_fips <- st_fp %>%
                    filter(Mainland_plus == 1) %>%
                    rename(region = "Postal Code")


csc <- read_csv("data/MERGED2018_19_PP.csv",
                na = c("", "NA", "NaN", "NULL", "Privacy Suppressed")) %>%
            filter(STABBR %in% desired_fips$region) %>%
            mutate(PELLCAT = case_when(PCTPELL < .5 ~ 0,
                                       PCTPELL >= .5 ~ 1))

csc$UNITID <- as.character(csc$UNITID)
csc$INSTNM <- as.character(csc$INSTNM)
csc$CITY <- as.character(csc$CITY)
csc$STABBR <- as.character(csc$STABBR)
csc$REGION <- as.character(csc$REGION)
csc$LATITUDE <- as.numeric(csc$LATITUDE)
csc$LONGITUDE <- as.numeric(csc$LONGITUDE)
csc$CURROPER <- as.character(csc$CURROPER)
csc$MAIN <- as.character(csc$MAIN)
csc$CONTROL <- as.character(csc$CONTROL)
csc$ICLEVEL <- as.character(csc$ICLEVEL)
csc$HIGHDEG <- as.character(csc$HIGHDEG)
csc$PREDDEG <- as.character(csc$PREDDEG)
csc$OPENADMP <- as.character(csc$OPENADMP)
csc$PCTPELL <- as.numeric(csc$PCTPELL)
csc$PCTFLOAN <- as.numeric(csc$PCTFLOAN)
csc$OPEID <- as.character(csc$OPEID)
csc$OPEID6 <- as.character(csc$OPEID6)
csc$ZIP <- as.character(csc$ZIP)
csc$ACCREDAGENCY <- as.character(csc$ACCREDAGENCY)
csc$INSTURL <- as.character(csc$INSTURL)
csc$NPCURL <- as.character(csc$NPCURL)
csc$HCM2 <- as.character(csc$HCM2)
csc$NUMBRANCH <- as.numeric(csc$NUMBRANCH)
csc$ST_FIPS <- as.character(csc$ST_FIPS)
csc$LOCALE <- as.character(csc$LOCALE)
csc$CCBASIC <- as.character(csc$CCBASIC)
csc$CCUGPROF <- as.character(csc$CCUGPROF)
csc$CCSIZSET <- as.character(csc$CCSIZSET)
csc$HBCU <- as.character(csc$HBCU)
csc$PBI <- as.character(csc$PBI)
csc$ANNHI <- as.character(csc$ANNHI)
csc$TRIBAL <- as.character(csc$TRIBAL)
csc$AANAPII <- as.character(csc$AANAPII)
csc$HSI <- as.character(csc$HSI)
csc$NANTI <- as.character(csc$NANTI)
csc$MENONLY <- as.character(csc$MENONLY)
csc$WOMENONLY <- as.character(csc$WOMENONLY)
csc$RELAFFIL <- as.character(csc$RELAFFIL)
csc$ADM_RATE <- as.numeric(csc$ADM_RATE)
csc$ADM_RATE_ALL <- as.numeric(csc$ADM_RATE_ALL)
csc$SATVR25 <- as.numeric(csc$SATVR25)
csc$SATVR75 <- as.numeric(csc$SATVR75)
csc$SATMT25 <- as.numeric(csc$SATMT25)
csc$SATMT75 <- as.numeric(csc$SATMT75)
csc$SATVRMID <- as.numeric(csc$SATVRMID)
csc$SATMTMID <- as.numeric(csc$SATMTMID)
csc$ACTCM25 <- as.numeric(csc$ACTCM25)
csc$ACTCM75 <- as.numeric(csc$ACTCM75)
csc$ACTEN25 <- as.numeric(csc$ACTEN25)
csc$ACTEN75 <- as.numeric(csc$ACTEN75)
csc$ACTMT25 <- as.numeric(csc$ACTMT25)
csc$ACTMT75 <- as.numeric(csc$ACTMT75)
csc$ACTCMMID <- as.numeric(csc$ACTCMMID)
csc$ACTENMID <- as.numeric(csc$ACTENMID)
csc$ACTMTMID <- as.numeric(csc$ACTMTMID)
csc$SAT_AVG <- as.numeric(csc$SAT_AVG)
csc$SAT_AVG_ALL <- as.numeric(csc$SAT_AVG_ALL)
csc$PCIP01 <- as.numeric(csc$PCIP01)
csc$PCIP03 <- as.numeric(csc$PCIP03)
csc$PCIP04 <- as.numeric(csc$PCIP04)
csc$PCIP05 <- as.numeric(csc$PCIP05)
csc$PCIP09 <- as.numeric(csc$PCIP09)
csc$PCIP10 <- as.numeric(csc$PCIP10)
csc$PCIP11 <- as.numeric(csc$PCIP11)
csc$PCIP12 <- as.numeric(csc$PCIP12)
csc$PCIP13 <- as.numeric(csc$PCIP13)
csc$PCIP14 <- as.numeric(csc$PCIP14)
csc$PCIP15 <- as.numeric(csc$PCIP15)
csc$PCIP16 <- as.numeric(csc$PCIP16)
csc$PCIP19 <- as.numeric(csc$PCIP19)
csc$PCIP22 <- as.numeric(csc$PCIP22)
csc$PCIP23 <- as.numeric(csc$PCIP23)
csc$PCIP24 <- as.numeric(csc$PCIP24)
csc$PCIP25 <- as.numeric(csc$PCIP25)
csc$PCIP26 <- as.numeric(csc$PCIP26)
csc$PCIP27 <- as.numeric(csc$PCIP27)
csc$PCIP29 <- as.numeric(csc$PCIP29)
csc$PCIP30 <- as.numeric(csc$PCIP30)
csc$PCIP31 <- as.numeric(csc$PCIP31)
csc$PCIP38 <- as.numeric(csc$PCIP38)
csc$PCIP39 <- as.numeric(csc$PCIP39)
csc$PCIP40 <- as.numeric(csc$PCIP40)
csc$PCIP41 <- as.numeric(csc$PCIP41)
csc$PCIP42 <- as.numeric(csc$PCIP42)
csc$PCIP43 <- as.numeric(csc$PCIP43)
csc$PCIP44 <- as.numeric(csc$PCIP44)
csc$PCIP45 <- as.numeric(csc$PCIP45)
csc$PCIP46 <- as.numeric(csc$PCIP46)
csc$PCIP47 <- as.numeric(csc$PCIP47)
csc$PCIP48 <- as.numeric(csc$PCIP48)
csc$PCIP49 <- as.numeric(csc$PCIP49)
csc$PCIP50 <- as.numeric(csc$PCIP50)
csc$PCIP51 <- as.numeric(csc$PCIP51)
csc$PCIP52 <- as.numeric(csc$PCIP52)
csc$PCIP54 <- as.numeric(csc$PCIP54)
csc$CIP01CERT1 <- as.factor(csc$CIP01CERT1)
csc$CIP01CERT2 <- as.factor(csc$CIP01CERT2)
csc$CIP01ASSOC <- as.factor(csc$CIP01ASSOC)
csc$CIP01CERT4 <- as.factor(csc$CIP01CERT4)
csc$CIP01BACHL <- as.factor(csc$CIP01BACHL)
csc$CIP03CERT1 <- as.factor(csc$CIP03CERT1)
csc$CIP03CERT2 <- as.factor(csc$CIP03CERT2)
csc$CIP03ASSOC <- as.factor(csc$CIP03ASSOC)
csc$CIP03CERT4 <- as.factor(csc$CIP03CERT4)
csc$CIP03BACHL <- as.factor(csc$CIP03BACHL)
csc$CIP04CERT1 <- as.factor(csc$CIP04CERT1)
csc$CIP04CERT2 <- as.factor(csc$CIP04CERT2)
csc$CIP04ASSOC <- as.factor(csc$CIP04ASSOC)
csc$CIP04CERT4 <- as.factor(csc$CIP04CERT4)
csc$CIP04BACHL <- as.factor(csc$CIP04BACHL)
csc$CIP05CERT1 <- as.factor(csc$CIP05CERT1)
csc$CIP05CERT2 <- as.factor(csc$CIP05CERT2)
csc$CIP05ASSOC <- as.factor(csc$CIP05ASSOC)
csc$CIP05CERT4 <- as.factor(csc$CIP05CERT4)
csc$CIP05BACHL <- as.factor(csc$CIP05BACHL)
csc$CIP09CERT1 <- as.factor(csc$CIP09CERT1)
csc$CIP09CERT2 <- as.factor(csc$CIP09CERT2)
csc$CIP09ASSOC <- as.factor(csc$CIP09ASSOC)
csc$CIP09CERT4 <- as.factor(csc$CIP09CERT4)
csc$CIP09BACHL <- as.factor(csc$CIP09BACHL)
csc$CIP10CERT1 <- as.factor(csc$CIP10CERT1)
csc$CIP10CERT2 <- as.factor(csc$CIP10CERT2)
csc$CIP10ASSOC <- as.factor(csc$CIP10ASSOC)
csc$CIP10CERT4 <- as.factor(csc$CIP10CERT4)
csc$CIP10BACHL <- as.factor(csc$CIP10BACHL)
csc$CIP11CERT1 <- as.factor(csc$CIP11CERT1)
csc$CIP11CERT2 <- as.factor(csc$CIP11CERT2)
csc$CIP11ASSOC <- as.factor(csc$CIP11ASSOC)
csc$CIP11CERT4 <- as.factor(csc$CIP11CERT4)
csc$CIP11BACHL <- as.factor(csc$CIP11BACHL)
csc$CIP12CERT1 <- as.factor(csc$CIP12CERT1)
csc$CIP12CERT2 <- as.factor(csc$CIP12CERT2)
csc$CIP12ASSOC <- as.factor(csc$CIP12ASSOC)
csc$CIP12CERT4 <- as.factor(csc$CIP12CERT4)
csc$CIP12BACHL <- as.factor(csc$CIP12BACHL)
csc$CIP13CERT1 <- as.factor(csc$CIP13CERT1)
csc$CIP13CERT2 <- as.factor(csc$CIP13CERT2)
csc$CIP13ASSOC <- as.factor(csc$CIP13ASSOC)
csc$CIP13CERT4 <- as.factor(csc$CIP13CERT4)
csc$CIP13BACHL <- as.factor(csc$CIP13BACHL)
csc$CIP14CERT1 <- as.factor(csc$CIP14CERT1)
csc$CIP14CERT2 <- as.factor(csc$CIP14CERT2)
csc$CIP14ASSOC <- as.factor(csc$CIP14ASSOC)
csc$CIP14CERT4 <- as.factor(csc$CIP14CERT4)
csc$CIP14BACHL <- as.factor(csc$CIP14BACHL)
csc$CIP15CERT1 <- as.factor(csc$CIP15CERT1)
csc$CIP15CERT2 <- as.factor(csc$CIP15CERT2)
csc$CIP15ASSOC <- as.factor(csc$CIP15ASSOC)
csc$CIP15CERT4 <- as.factor(csc$CIP15CERT4)
csc$CIP15BACHL <- as.factor(csc$CIP15BACHL)
csc$CIP16CERT1 <- as.factor(csc$CIP16CERT1)
csc$CIP16CERT2 <- as.factor(csc$CIP16CERT2)
csc$CIP16ASSOC <- as.factor(csc$CIP16ASSOC)
csc$CIP16CERT4 <- as.factor(csc$CIP16CERT4)
csc$CIP16BACHL <- as.factor(csc$CIP16BACHL)
csc$CIP19CERT1 <- as.factor(csc$CIP19CERT1)
csc$CIP19CERT2 <- as.factor(csc$CIP19CERT2)
csc$CIP19ASSOC <- as.factor(csc$CIP19ASSOC)
csc$CIP19CERT4 <- as.factor(csc$CIP19CERT4)
csc$CIP19BACHL <- as.factor(csc$CIP19BACHL)
csc$CIP22CERT1 <- as.factor(csc$CIP22CERT1)
csc$CIP22CERT2 <- as.factor(csc$CIP22CERT2)
csc$CIP22ASSOC <- as.factor(csc$CIP22ASSOC)
csc$CIP22CERT4 <- as.factor(csc$CIP22CERT4)
csc$CIP22BACHL <- as.factor(csc$CIP22BACHL)
csc$CIP23CERT1 <- as.factor(csc$CIP23CERT1)
csc$CIP23CERT2 <- as.factor(csc$CIP23CERT2)
csc$CIP23ASSOC <- as.factor(csc$CIP23ASSOC)
csc$CIP23CERT4 <- as.factor(csc$CIP23CERT4)
csc$CIP23BACHL <- as.factor(csc$CIP23BACHL)
csc$CIP24CERT1 <- as.factor(csc$CIP24CERT1)
csc$CIP24CERT2 <- as.factor(csc$CIP24CERT2)
csc$CIP24ASSOC <- as.factor(csc$CIP24ASSOC)
csc$CIP24CERT4 <- as.factor(csc$CIP24CERT4)
csc$CIP24BACHL <- as.factor(csc$CIP24BACHL)
csc$CIP25CERT1 <- as.factor(csc$CIP25CERT1)
csc$CIP25CERT2 <- as.factor(csc$CIP25CERT2)
csc$CIP25ASSOC <- as.factor(csc$CIP25ASSOC)
csc$CIP25CERT4 <- as.factor(csc$CIP25CERT4)
csc$CIP25BACHL <- as.factor(csc$CIP25BACHL)
csc$CIP26CERT1 <- as.factor(csc$CIP26CERT1)
csc$CIP26CERT2 <- as.factor(csc$CIP26CERT2)
csc$CIP26ASSOC <- as.factor(csc$CIP26ASSOC)
csc$CIP26CERT4 <- as.factor(csc$CIP26CERT4)
csc$CIP26BACHL <- as.factor(csc$CIP26BACHL)
csc$CIP27CERT1 <- as.factor(csc$CIP27CERT1)
csc$CIP27CERT2 <- as.factor(csc$CIP27CERT2)
csc$CIP27ASSOC <- as.factor(csc$CIP27ASSOC)
csc$CIP27CERT4 <- as.factor(csc$CIP27CERT4)
csc$CIP27BACHL <- as.factor(csc$CIP27BACHL)
csc$CIP29CERT1 <- as.factor(csc$CIP29CERT1)
csc$CIP29CERT2 <- as.factor(csc$CIP29CERT2)
csc$CIP29ASSOC <- as.factor(csc$CIP29ASSOC)
csc$CIP29CERT4 <- as.factor(csc$CIP29CERT4)
csc$CIP29BACHL <- as.factor(csc$CIP29BACHL)
csc$CIP30CERT1 <- as.factor(csc$CIP30CERT1)
csc$CIP30CERT2 <- as.factor(csc$CIP30CERT2)
csc$CIP30ASSOC <- as.factor(csc$CIP30ASSOC)
csc$CIP30CERT4 <- as.factor(csc$CIP30CERT4)
csc$CIP30BACHL <- as.factor(csc$CIP30BACHL)
csc$CIP31CERT1 <- as.factor(csc$CIP31CERT1)
csc$CIP31CERT2 <- as.factor(csc$CIP31CERT2)
csc$CIP31ASSOC <- as.factor(csc$CIP31ASSOC)
csc$CIP31CERT4 <- as.factor(csc$CIP31CERT4)
csc$CIP31BACHL <- as.factor(csc$CIP31BACHL)
csc$CIP38CERT1 <- as.factor(csc$CIP38CERT1)
csc$CIP38CERT2 <- as.factor(csc$CIP38CERT2)
csc$CIP38ASSOC <- as.factor(csc$CIP38ASSOC)
csc$CIP38CERT4 <- as.factor(csc$CIP38CERT4)
csc$CIP38BACHL <- as.factor(csc$CIP38BACHL)
csc$CIP39CERT1 <- as.factor(csc$CIP39CERT1)
csc$CIP39CERT2 <- as.factor(csc$CIP39CERT2)
csc$CIP39ASSOC <- as.factor(csc$CIP39ASSOC)
csc$CIP39CERT4 <- as.factor(csc$CIP39CERT4)
csc$CIP39BACHL <- as.factor(csc$CIP39BACHL)
csc$CIP40CERT1 <- as.factor(csc$CIP40CERT1)
csc$CIP40CERT2 <- as.factor(csc$CIP40CERT2)
csc$CIP40ASSOC <- as.factor(csc$CIP40ASSOC)
csc$CIP40CERT4 <- as.factor(csc$CIP40CERT4)
csc$CIP40BACHL <- as.factor(csc$CIP40BACHL)
csc$CIP41CERT1 <- as.factor(csc$CIP41CERT1)
csc$CIP41CERT2 <- as.factor(csc$CIP41CERT2)
csc$CIP41ASSOC <- as.factor(csc$CIP41ASSOC)
csc$CIP41CERT4 <- as.factor(csc$CIP41CERT4)
csc$CIP41BACHL <- as.factor(csc$CIP41BACHL)
csc$CIP42CERT1 <- as.factor(csc$CIP42CERT1)
csc$CIP42CERT2 <- as.factor(csc$CIP42CERT2)
csc$CIP42ASSOC <- as.factor(csc$CIP42ASSOC)
csc$CIP42CERT4 <- as.factor(csc$CIP42CERT4)
csc$CIP42BACHL <- as.factor(csc$CIP42BACHL)
csc$CIP43CERT1 <- as.factor(csc$CIP43CERT1)
csc$CIP43CERT2 <- as.factor(csc$CIP43CERT2)
csc$CIP43ASSOC <- as.factor(csc$CIP43ASSOC)
csc$CIP43CERT4 <- as.factor(csc$CIP43CERT4)
csc$CIP43BACHL <- as.factor(csc$CIP43BACHL)
csc$CIP44CERT1 <- as.factor(csc$CIP44CERT1)
csc$CIP44CERT2 <- as.factor(csc$CIP44CERT2)
csc$CIP44ASSOC <- as.factor(csc$CIP44ASSOC)
csc$CIP44CERT4 <- as.factor(csc$CIP44CERT4)
csc$CIP44BACHL <- as.factor(csc$CIP44BACHL)
csc$CIP45CERT1 <- as.factor(csc$CIP45CERT1)
csc$CIP45CERT2 <- as.factor(csc$CIP45CERT2)
csc$CIP45ASSOC <- as.factor(csc$CIP45ASSOC)
csc$CIP45CERT4 <- as.factor(csc$CIP45CERT4)
csc$CIP45BACHL <- as.factor(csc$CIP45BACHL)
csc$CIP46CERT1 <- as.factor(csc$CIP46CERT1)
csc$CIP46CERT2 <- as.factor(csc$CIP46CERT2)
csc$CIP46ASSOC <- as.factor(csc$CIP46ASSOC)
csc$CIP46CERT4 <- as.factor(csc$CIP46CERT4)
csc$CIP46BACHL <- as.factor(csc$CIP46BACHL)
csc$CIP47CERT1 <- as.factor(csc$CIP47CERT1)
csc$CIP47CERT2 <- as.factor(csc$CIP47CERT2)
csc$CIP47ASSOC <- as.factor(csc$CIP47ASSOC)
csc$CIP47CERT4 <- as.factor(csc$CIP47CERT4)
csc$CIP47BACHL <- as.factor(csc$CIP47BACHL)
csc$CIP48CERT1 <- as.factor(csc$CIP48CERT1)
csc$CIP48CERT2 <- as.factor(csc$CIP48CERT2)
csc$CIP48ASSOC <- as.factor(csc$CIP48ASSOC)
csc$CIP48CERT4 <- as.factor(csc$CIP48CERT4)
csc$CIP48BACHL <- as.factor(csc$CIP48BACHL)
csc$CIP49CERT1 <- as.factor(csc$CIP49CERT1)
csc$CIP49CERT2 <- as.factor(csc$CIP49CERT2)
csc$CIP49ASSOC <- as.factor(csc$CIP49ASSOC)
csc$CIP49CERT4 <- as.factor(csc$CIP49CERT4)
csc$CIP49BACHL <- as.factor(csc$CIP49BACHL)
csc$CIP50CERT1 <- as.factor(csc$CIP50CERT1)
csc$CIP50CERT2 <- as.factor(csc$CIP50CERT2)
csc$CIP50ASSOC <- as.factor(csc$CIP50ASSOC)
csc$CIP50CERT4 <- as.factor(csc$CIP50CERT4)
csc$CIP50BACHL <- as.factor(csc$CIP50BACHL)
csc$CIP51CERT1 <- as.factor(csc$CIP51CERT1)
csc$CIP51CERT2 <- as.factor(csc$CIP51CERT2)
csc$CIP51ASSOC <- as.factor(csc$CIP51ASSOC)
csc$CIP51CERT4 <- as.factor(csc$CIP51CERT4)
csc$CIP51BACHL <- as.factor(csc$CIP51BACHL)
csc$CIP52CERT1 <- as.factor(csc$CIP52CERT1)
csc$CIP52CERT2 <- as.factor(csc$CIP52CERT2)
csc$CIP52ASSOC <- as.factor(csc$CIP52ASSOC)
csc$CIP52CERT4 <- as.factor(csc$CIP52CERT4)
csc$CIP52BACHL <- as.factor(csc$CIP52BACHL)
csc$CIP54CERT1 <- as.factor(csc$CIP54CERT1)
csc$CIP54CERT2 <- as.factor(csc$CIP54CERT2)
csc$CIP54ASSOC <- as.factor(csc$CIP54ASSOC)
csc$CIP54CERT4 <- as.factor(csc$CIP54CERT4)
csc$CIP54BACHL <- as.factor(csc$CIP54BACHL)
csc$DISTANCEONLY <- as.character(csc$DISTANCEONLY)
csc$UGDS <- as.numeric(csc$UGDS)
csc$UGDS_WHITE <- as.numeric(csc$UGDS_WHITE)
csc$UGDS_BLACK <- as.numeric(csc$UGDS_BLACK)
csc$UGDS_HISP <- as.numeric(csc$UGDS_HISP)
csc$UGDS_ASIAN <- as.numeric(csc$UGDS_ASIAN)
csc$UGDS_AIAN <- as.numeric(csc$UGDS_AIAN)
csc$UGDS_NHPI <- as.numeric(csc$UGDS_NHPI)
csc$UGDS_2MOR <- as.numeric(csc$UGDS_2MOR)
csc$UGDS_NRA <- as.numeric(csc$UGDS_NRA)
csc$UGDS_UNKN <- as.numeric(csc$UGDS_UNKN)
csc$PPTUG_EF <- as.numeric(csc$PPTUG_EF)
csc$NPT4_PUB <- as.numeric(csc$NPT4_PUB)
csc$NPT4_PRIV <- as.numeric(csc$NPT4_PRIV)
csc$NPT41_PUB <- as.numeric(csc$NPT41_PUB)
csc$NPT42_PUB <- as.numeric(csc$NPT42_PUB)
csc$NPT43_PUB <- as.numeric(csc$NPT43_PUB)
csc$NPT44_PUB <- as.numeric(csc$NPT44_PUB)
csc$NPT45_PUB <- as.numeric(csc$NPT45_PUB)
csc$NPT41_PRIV <- as.numeric(csc$NPT41_PRIV)
csc$NPT42_PRIV <- as.numeric(csc$NPT42_PRIV)
csc$NPT43_PRIV <- as.numeric(csc$NPT43_PRIV)
csc$NPT44_PRIV <- as.numeric(csc$NPT44_PRIV)
csc$NPT45_PRIV <- as.numeric(csc$NPT45_PRIV)
csc$NPT4_048_PUB <- as.numeric(csc$NPT4_048_PUB)
csc$NPT4_048_PRIV <- as.numeric(csc$NPT4_048_PRIV)
csc$NPT4_3075_PUB <- as.numeric(csc$NPT4_3075_PUB)
csc$NPT4_3075_PRIV <- as.numeric(csc$NPT4_3075_PRIV)
csc$NPT4_75UP_PUB <- as.numeric(csc$NPT4_75UP_PUB)
csc$NPT4_75UP_PRIV <- as.numeric(csc$NPT4_75UP_PRIV)
csc$NUM4_PUB <- as.numeric(csc$NUM4_PUB)
csc$NUM4_PRIV <- as.numeric(csc$NUM4_PRIV)
csc$NUM41_PUB <- as.numeric(csc$NUM41_PUB)
csc$NUM42_PUB <- as.numeric(csc$NUM42_PUB)
csc$NUM43_PUB <- as.numeric(csc$NUM43_PUB)
csc$NUM44_PUB <- as.numeric(csc$NUM44_PUB)
csc$NUM45_PUB <- as.numeric(csc$NUM45_PUB)
csc$NUM41_PRIV <- as.numeric(csc$NUM41_PRIV)
csc$NUM42_PRIV <- as.numeric(csc$NUM42_PRIV)
csc$NUM43_PRIV <- as.numeric(csc$NUM43_PRIV)
csc$NUM44_PRIV <- as.numeric(csc$NUM44_PRIV)
csc$NUM45_PRIV <- as.numeric(csc$NUM45_PRIV)
csc$COSTT4_A <- as.numeric(csc$COSTT4_A)
csc$COSTT4_P <- as.numeric(csc$COSTT4_P)
csc$TUITIONFEE_IN <- as.numeric(csc$TUITIONFEE_IN)
csc$TUITIONFEE_OUT <- as.numeric(csc$TUITIONFEE_OUT)
csc$TUITIONFEE_PROG <- as.numeric(csc$TUITIONFEE_PROG)
csc$TUITFTE <- as.numeric(csc$TUITFTE)
csc$INEXPFTE <- as.numeric(csc$INEXPFTE)
csc$AVGFACSAL <- as.numeric(csc$AVGFACSAL)
csc$PFTFAC <- as.numeric(csc$PFTFAC)
csc$C150_4 <- as.numeric(csc$C150_4)
csc$C150_L4 <- as.numeric(csc$C150_L4)
csc$C150_4_POOLED <- as.numeric(csc$C150_4_POOLED)
csc$C150_L4_POOLED <- as.numeric(csc$C150_L4_POOLED)
csc$POOLYRS <- as.numeric(csc$POOLYRS)
csc$PFTFTUG1_EF <- as.numeric(csc$PFTFTUG1_EF)
csc$D150_4 <- as.numeric(csc$D150_4)
csc$D150_L4 <- as.numeric(csc$D150_L4)
csc$D150_4_POOLED <- as.numeric(csc$D150_4_POOLED)
csc$D150_L4_POOLED <- as.numeric(csc$D150_L4_POOLED)
csc$C150_4_WHITE <- as.numeric(csc$C150_4_WHITE)
csc$C150_4_BLACK <- as.numeric(csc$C150_4_BLACK)
csc$C150_4_HISP <- as.numeric(csc$C150_4_HISP)
csc$C150_4_ASIAN <- as.numeric(csc$C150_4_ASIAN)
csc$C150_4_AIAN <- as.numeric(csc$C150_4_AIAN)
csc$C150_4_NHPI <- as.numeric(csc$C150_4_NHPI)
csc$C150_4_2MOR <- as.numeric(csc$C150_4_2MOR)
csc$C150_4_NRA <- as.numeric(csc$C150_4_NRA)
csc$C150_4_UNKN <- as.numeric(csc$C150_4_UNKN)
csc$C150_L4_WHITE <- as.numeric(csc$C150_L4_WHITE)
csc$C150_L4_BLACK <- as.numeric(csc$C150_L4_BLACK)
csc$C150_L4_HISP <- as.numeric(csc$C150_L4_HISP)
csc$C150_L4_ASIAN <- as.numeric(csc$C150_L4_ASIAN)
csc$C150_L4_AIAN <- as.numeric(csc$C150_L4_AIAN)
csc$C150_L4_NHPI <- as.numeric(csc$C150_L4_NHPI)
csc$C150_L4_2MOR <- as.numeric(csc$C150_L4_2MOR)
csc$C150_L4_NRA <- as.numeric(csc$C150_L4_NRA)
csc$C150_L4_UNKN <- as.numeric(csc$C150_L4_UNKN)
csc$C200_4 <- as.numeric(csc$C200_4)
csc$C200_L4 <- as.numeric(csc$C200_L4)
csc$D200_4 <- as.numeric(csc$D200_4)
csc$D200_L4 <- as.numeric(csc$D200_L4)
csc$RET_FT4 <- as.numeric(csc$RET_FT4)
csc$RET_FTL4 <- as.numeric(csc$RET_FTL4)
csc$RET_PT4 <- as.numeric(csc$RET_PT4)
csc$RET_PTL4 <- as.numeric(csc$RET_PTL4)
csc$C200_4_POOLED <- as.numeric(csc$C200_4_POOLED)
csc$C200_L4_POOLED <- as.numeric(csc$C200_L4_POOLED)
csc$POOLYRS200 <- as.numeric(csc$POOLYRS200)
csc$D200_4_POOLED <- as.numeric(csc$D200_4_POOLED)
csc$D200_L4_POOLED <- as.numeric(csc$D200_L4_POOLED)
csc$CDR3 <- as.numeric(csc$CDR3)
csc$DEBT_MDN <- as.numeric(csc$DEBT_MDN)
csc$GRAD_DEBT_MDN <- as.numeric(csc$GRAD_DEBT_MDN)
csc$WDRAW_DEBT_MDN <- as.numeric(csc$WDRAW_DEBT_MDN)
csc$LO_INC_DEBT_MDN <- as.numeric(csc$LO_INC_DEBT_MDN)
csc$MD_INC_DEBT_MDN <- as.numeric(csc$MD_INC_DEBT_MDN)
csc$HI_INC_DEBT_MDN <- as.numeric(csc$HI_INC_DEBT_MDN)
csc$DEP_DEBT_MDN <- as.numeric(csc$DEP_DEBT_MDN)
csc$IND_DEBT_MDN <- as.numeric(csc$IND_DEBT_MDN)
csc$PELL_DEBT_MDN <- as.numeric(csc$PELL_DEBT_MDN)
csc$NOPELL_DEBT_MDN <- as.numeric(csc$NOPELL_DEBT_MDN)
csc$FEMALE_DEBT_MDN <- as.numeric(csc$FEMALE_DEBT_MDN)
csc$MALE_DEBT_MDN <- as.numeric(csc$MALE_DEBT_MDN)
csc$FIRSTGEN_DEBT_MDN <- as.numeric(csc$FIRSTGEN_DEBT_MDN)
csc$NOTFIRSTGEN_DEBT_MDN <- as.numeric(csc$NOTFIRSTGEN_DEBT_MDN)
csc$DEBT_N <- as.numeric(csc$DEBT_N)
csc$GRAD_DEBT_N <- as.numeric(csc$GRAD_DEBT_N)
csc$WDRAW_DEBT_N <- as.numeric(csc$WDRAW_DEBT_N)
csc$LO_INC_DEBT_N <- as.numeric(csc$LO_INC_DEBT_N)
csc$MD_INC_DEBT_N <- as.numeric(csc$MD_INC_DEBT_N)
csc$HI_INC_DEBT_N <- as.numeric(csc$HI_INC_DEBT_N)
csc$DEP_DEBT_N <- as.numeric(csc$DEP_DEBT_N)
csc$IND_DEBT_N <- as.numeric(csc$IND_DEBT_N)
csc$PELL_DEBT_N <- as.numeric(csc$PELL_DEBT_N)
csc$NOPELL_DEBT_N <- as.numeric(csc$NOPELL_DEBT_N)
csc$FEMALE_DEBT_N <- as.numeric(csc$FEMALE_DEBT_N)
csc$MALE_DEBT_N <- as.numeric(csc$MALE_DEBT_N)
csc$FIRSTGEN_DEBT_N <- as.numeric(csc$FIRSTGEN_DEBT_N)
csc$NOTFIRSTGEN_DEBT_N <- as.numeric(csc$NOTFIRSTGEN_DEBT_N)
csc$GRAD_DEBT_MDN10YR <- as.numeric(csc$GRAD_DEBT_MDN10YR)
csc$DEBT_MDN_SUPP <- as.numeric(csc$DEBT_MDN_SUPP)
csc$GRAD_DEBT_MDN_SUPP <- as.numeric(csc$GRAD_DEBT_MDN_SUPP)
csc$GRAD_DEBT_MDN10YR_SUPP <- as.numeric(csc$GRAD_DEBT_MDN10YR_SUPP)
csc$C150_L4_POOLED_SUPP <- as.numeric(csc$C150_L4_POOLED_SUPP)
csc$C150_4_POOLED_SUPP <- as.numeric(csc$C150_4_POOLED_SUPP)
csc$C200_L4_POOLED_SUPP <- as.numeric(csc$C200_L4_POOLED_SUPP)
csc$C200_4_POOLED_SUPP <- as.numeric(csc$C200_4_POOLED_SUPP)
csc$ALIAS <- as.character(csc$ALIAS)
csc$C100_4 <- as.numeric(csc$C100_4)
csc$D100_4 <- as.numeric(csc$D100_4)
csc$C100_L4 <- as.numeric(csc$C100_L4)
csc$D100_L4 <- as.numeric(csc$D100_L4)
csc$TRANS_4 <- as.numeric(csc$TRANS_4)
csc$DTRANS_4 <- as.numeric(csc$DTRANS_4)
csc$TRANS_L4 <- as.numeric(csc$TRANS_L4)
csc$DTRANS_L4 <- as.numeric(csc$DTRANS_L4)
csc$UGDS_MEN <- as.numeric(csc$UGDS_MEN)
csc$UGDS_WOMEN <- as.numeric(csc$UGDS_WOMEN)
csc$CDR3_DENOM <- as.numeric(csc$CDR3_DENOM)
csc$T4APPROVALDATE <- as.character(csc$T4APPROVALDATE)
csc$D150_4_WHITE <- as.numeric(csc$D150_4_WHITE)
csc$D150_4_BLACK <- as.numeric(csc$D150_4_BLACK)
csc$D150_4_HISP <- as.numeric(csc$D150_4_HISP)
csc$D150_4_ASIAN <- as.numeric(csc$D150_4_ASIAN)
csc$D150_4_AIAN <- as.numeric(csc$D150_4_AIAN)
csc$D150_4_NHPI <- as.numeric(csc$D150_4_NHPI)
csc$D150_4_2MOR <- as.numeric(csc$D150_4_2MOR)
csc$D150_4_NRA <- as.numeric(csc$D150_4_NRA)
csc$D150_4_UNKN <- as.numeric(csc$D150_4_UNKN)
csc$D150_L4_WHITE <- as.numeric(csc$D150_L4_WHITE)
csc$D150_L4_BLACK <- as.numeric(csc$D150_L4_BLACK)
csc$D150_L4_HISP <- as.numeric(csc$D150_L4_HISP)
csc$D150_L4_ASIAN <- as.numeric(csc$D150_L4_ASIAN)
csc$D150_L4_AIAN <- as.numeric(csc$D150_L4_AIAN)
csc$D150_L4_NHPI <- as.numeric(csc$D150_L4_NHPI)
csc$D150_L4_2MOR <- as.numeric(csc$D150_L4_2MOR)
csc$D150_L4_NRA <- as.numeric(csc$D150_L4_NRA)
csc$D150_L4_UNKN <- as.numeric(csc$D150_L4_UNKN)
csc$D_PCTPELL_PCTFLOAN <- as.numeric(csc$D_PCTPELL_PCTFLOAN)
csc$UGNONDS <- as.numeric(csc$UGNONDS)
csc$GRADS <- as.numeric(csc$GRADS)
csc$ACCREDCODE <- as.character(csc$ACCREDCODE)
csc$OMACHT6_FTFT <- as.numeric(csc$OMACHT6_FTFT)
csc$OMAWDP6_FTFT <- as.numeric(csc$OMAWDP6_FTFT)
csc$OMACHT8_FTFT <- as.numeric(csc$OMACHT8_FTFT)
csc$OMAWDP8_FTFT <- as.numeric(csc$OMAWDP8_FTFT)
csc$OMENRYP8_FTFT <- as.numeric(csc$OMENRYP8_FTFT)
csc$OMENRAP8_FTFT <- as.numeric(csc$OMENRAP8_FTFT)
csc$OMENRUP8_FTFT <- as.numeric(csc$OMENRUP8_FTFT)
csc$OMACHT6_PTFT <- as.numeric(csc$OMACHT6_PTFT)
csc$OMAWDP6_PTFT <- as.numeric(csc$OMAWDP6_PTFT)
csc$OMACHT8_PTFT <- as.numeric(csc$OMACHT8_PTFT)
csc$OMAWDP8_PTFT <- as.numeric(csc$OMAWDP8_PTFT)
csc$OMENRYP8_PTFT <- as.numeric(csc$OMENRYP8_PTFT)
csc$OMENRAP8_PTFT <- as.numeric(csc$OMENRAP8_PTFT)
csc$OMENRUP8_PTFT <- as.numeric(csc$OMENRUP8_PTFT)
csc$OMACHT6_FTNFT <- as.numeric(csc$OMACHT6_FTNFT)
csc$OMAWDP6_FTNFT <- as.numeric(csc$OMAWDP6_FTNFT)
csc$OMACHT8_FTNFT <- as.numeric(csc$OMACHT8_FTNFT)
csc$OMAWDP8_FTNFT <- as.numeric(csc$OMAWDP8_FTNFT)
csc$OMENRYP8_FTNFT <- as.numeric(csc$OMENRYP8_FTNFT)
csc$OMENRAP8_FTNFT <- as.numeric(csc$OMENRAP8_FTNFT)
csc$OMENRUP8_FTNFT <- as.numeric(csc$OMENRUP8_FTNFT)
csc$OMACHT6_PTNFT <- as.numeric(csc$OMACHT6_PTNFT)
csc$OMAWDP6_PTNFT <- as.numeric(csc$OMAWDP6_PTNFT)
csc$OMACHT8_PTNFT <- as.numeric(csc$OMACHT8_PTNFT)
csc$OMAWDP8_PTNFT <- as.numeric(csc$OMAWDP8_PTNFT)
csc$OMENRYP8_PTNFT <- as.numeric(csc$OMENRYP8_PTNFT)
csc$OMENRAP8_PTNFT <- as.numeric(csc$OMENRAP8_PTNFT)
csc$OMENRUP8_PTNFT <- as.numeric(csc$OMENRUP8_PTNFT)
csc$RET_FT4_POOLED <- as.numeric(csc$RET_FT4_POOLED)
csc$RET_FTL4_POOLED <- as.numeric(csc$RET_FTL4_POOLED)
csc$RET_PT4_POOLED <- as.numeric(csc$RET_PT4_POOLED)
csc$RET_PTL4_POOLED <- as.numeric(csc$RET_PTL4_POOLED)
csc$RET_FT_DEN4_POOLED <- as.numeric(csc$RET_FT_DEN4_POOLED)
csc$RET_FT_DENL4_POOLED <- as.numeric(csc$RET_FT_DENL4_POOLED)
csc$RET_PT_DEN4_POOLED <- as.numeric(csc$RET_PT_DEN4_POOLED)
csc$RET_PT_DENL4_POOLED <- as.numeric(csc$RET_PT_DENL4_POOLED)
csc$POOLYRSRET_FT <- as.numeric(csc$POOLYRSRET_FT)
csc$POOLYRSRET_PT <- as.numeric(csc$POOLYRSRET_PT)
csc$RET_FT4_POOLED_SUPP <- as.numeric(csc$RET_FT4_POOLED_SUPP)
csc$RET_FTL4_POOLED_SUPP <- as.numeric(csc$RET_FTL4_POOLED_SUPP)
csc$RET_PT4_POOLED_SUPP <- as.numeric(csc$RET_PT4_POOLED_SUPP)
csc$RET_PTL4_POOLED_SUPP <- as.numeric(csc$RET_PTL4_POOLED_SUPP)
csc$TRANS_4_POOLED <- as.numeric(csc$TRANS_4_POOLED)
csc$TRANS_L4_POOLED <- as.numeric(csc$TRANS_L4_POOLED)
csc$DTRANS_4_POOLED <- as.numeric(csc$DTRANS_4_POOLED)
csc$DTRANS_L4_POOLED <- as.numeric(csc$DTRANS_L4_POOLED)
csc$TRANS_4_POOLED_SUPP <- as.numeric(csc$TRANS_4_POOLED_SUPP)
csc$TRANS_L4_POOLED_SUPP <- as.numeric(csc$TRANS_L4_POOLED_SUPP)
csc$C100_4_POOLED <- as.numeric(csc$C100_4_POOLED)
csc$C100_L4_POOLED <- as.numeric(csc$C100_L4_POOLED)
csc$D100_4_POOLED <- as.numeric(csc$D100_4_POOLED)
csc$D100_L4_POOLED <- as.numeric(csc$D100_L4_POOLED)
csc$POOLYRS100 <- as.numeric(csc$POOLYRS100)
csc$C100_4_POOLED_SUPP <- as.numeric(csc$C100_4_POOLED_SUPP)
csc$C100_L4_POOLED_SUPP <- as.numeric(csc$C100_L4_POOLED_SUPP)
csc$C150_4_PELL <- as.numeric(csc$C150_4_PELL)
csc$D150_4_PELL <- as.numeric(csc$D150_4_PELL)
csc$C150_L4_PELL <- as.numeric(csc$C150_L4_PELL)
csc$D150_L4_PELL <- as.numeric(csc$D150_L4_PELL)
csc$C150_4_LOANNOPELL <- as.numeric(csc$C150_4_LOANNOPELL)
csc$D150_4_LOANNOPELL <- as.numeric(csc$D150_4_LOANNOPELL)
csc$C150_L4_LOANNOPELL <- as.numeric(csc$C150_L4_LOANNOPELL)
csc$D150_L4_LOANNOPELL <- as.numeric(csc$D150_L4_LOANNOPELL)
csc$C150_4_NOLOANNOPELL <- as.numeric(csc$C150_4_NOLOANNOPELL)
csc$D150_4_NOLOANNOPELL <- as.numeric(csc$D150_4_NOLOANNOPELL)
csc$C150_L4_NOLOANNOPELL <- as.numeric(csc$C150_L4_NOLOANNOPELL)
csc$D150_L4_NOLOANNOPELL <- as.numeric(csc$D150_L4_NOLOANNOPELL)
csc$OMACHT6_FTFT_POOLED <- as.numeric(csc$OMACHT6_FTFT_POOLED)
csc$OMAWDP6_FTFT_POOLED <- as.numeric(csc$OMAWDP6_FTFT_POOLED)
csc$OMACHT8_FTFT_POOLED <- as.numeric(csc$OMACHT8_FTFT_POOLED)
csc$OMAWDP8_FTFT_POOLED <- as.numeric(csc$OMAWDP8_FTFT_POOLED)
csc$OMENRYP8_FTFT_POOLED <- as.numeric(csc$OMENRYP8_FTFT_POOLED)
csc$OMENRAP8_FTFT_POOLED <- as.numeric(csc$OMENRAP8_FTFT_POOLED)
csc$OMENRUP8_FTFT_POOLED <- as.numeric(csc$OMENRUP8_FTFT_POOLED)
csc$OMACHT6_PTFT_POOLED <- as.numeric(csc$OMACHT6_PTFT_POOLED)
csc$OMAWDP6_PTFT_POOLED <- as.numeric(csc$OMAWDP6_PTFT_POOLED)
csc$OMACHT8_PTFT_POOLED <- as.numeric(csc$OMACHT8_PTFT_POOLED)
csc$OMAWDP8_PTFT_POOLED <- as.numeric(csc$OMAWDP8_PTFT_POOLED)
csc$OMENRYP8_PTFT_POOLED <- as.numeric(csc$OMENRYP8_PTFT_POOLED)
csc$OMENRAP8_PTFT_POOLED <- as.numeric(csc$OMENRAP8_PTFT_POOLED)
csc$OMENRUP8_PTFT_POOLED <- as.numeric(csc$OMENRUP8_PTFT_POOLED)
csc$OMACHT6_FTNFT_POOLED <- as.numeric(csc$OMACHT6_FTNFT_POOLED)
csc$OMAWDP6_FTNFT_POOLED <- as.numeric(csc$OMAWDP6_FTNFT_POOLED)
csc$OMACHT8_FTNFT_POOLED <- as.numeric(csc$OMACHT8_FTNFT_POOLED)
csc$OMAWDP8_FTNFT_POOLED <- as.numeric(csc$OMAWDP8_FTNFT_POOLED)
csc$OMENRYP8_FTNFT_POOLED <- as.numeric(csc$OMENRYP8_FTNFT_POOLED)
csc$OMENRAP8_FTNFT_POOLED <- as.numeric(csc$OMENRAP8_FTNFT_POOLED)
csc$OMENRUP8_FTNFT_POOLED <- as.numeric(csc$OMENRUP8_FTNFT_POOLED)
csc$OMACHT6_PTNFT_POOLED <- as.numeric(csc$OMACHT6_PTNFT_POOLED)
csc$OMAWDP6_PTNFT_POOLED <- as.numeric(csc$OMAWDP6_PTNFT_POOLED)
csc$OMACHT8_PTNFT_POOLED <- as.numeric(csc$OMACHT8_PTNFT_POOLED)
csc$OMAWDP8_PTNFT_POOLED <- as.numeric(csc$OMAWDP8_PTNFT_POOLED)
csc$OMENRYP8_PTNFT_POOLED <- as.numeric(csc$OMENRYP8_PTNFT_POOLED)
csc$OMENRAP8_PTNFT_POOLED <- as.numeric(csc$OMENRAP8_PTNFT_POOLED)
csc$OMENRUP8_PTNFT_POOLED <- as.numeric(csc$OMENRUP8_PTNFT_POOLED)
csc$POOLYRSOM_FTFT <- as.numeric(csc$POOLYRSOM_FTFT)
csc$POOLYRSOM_PTFT <- as.numeric(csc$POOLYRSOM_PTFT)
csc$POOLYRSOM_FTNFT <- as.numeric(csc$POOLYRSOM_FTNFT)
csc$POOLYRSOM_PTNFT <- as.numeric(csc$POOLYRSOM_PTNFT)
csc$OMAWDP6_FTFT_POOLED_SUPP <- as.numeric(csc$OMAWDP6_FTFT_POOLED_SUPP)
csc$OMAWDP8_FTFT_POOLED_SUPP <- as.numeric(csc$OMAWDP8_FTFT_POOLED_SUPP)
csc$OMENRYP8_FTFT_POOLED_SUPP <- as.numeric(csc$OMENRYP8_FTFT_POOLED_SUPP)
csc$OMENRAP8_FTFT_POOLED_SUPP <- as.numeric(csc$OMENRAP8_FTFT_POOLED_SUPP)
csc$OMENRUP8_FTFT_POOLED_SUPP <- as.numeric(csc$OMENRUP8_FTFT_POOLED_SUPP)
csc$OMAWDP6_PTFT_POOLED_SUPP <- as.numeric(csc$OMAWDP6_PTFT_POOLED_SUPP)
csc$OMAWDP8_PTFT_POOLED_SUPP <- as.numeric(csc$OMAWDP8_PTFT_POOLED_SUPP)
csc$OMENRYP8_PTFT_POOLED_SUPP <- as.numeric(csc$OMENRYP8_PTFT_POOLED_SUPP)
csc$OMENRAP8_PTFT_POOLED_SUPP <- as.numeric(csc$OMENRAP8_PTFT_POOLED_SUPP)
csc$OMENRUP8_PTFT_POOLED_SUPP <- as.numeric(csc$OMENRUP8_PTFT_POOLED_SUPP)
csc$OMAWDP6_FTNFT_POOLED_SUPP <- as.numeric(csc$OMAWDP6_FTNFT_POOLED_SUPP)
csc$OMAWDP8_FTNFT_POOLED_SUPP <- as.numeric(csc$OMAWDP8_FTNFT_POOLED_SUPP)
csc$OMENRYP8_FTNFT_POOLED_SUPP <- as.numeric(csc$OMENRYP8_FTNFT_POOLED_SUPP)
csc$OMENRAP8_FTNFT_POOLED_SUPP <- as.numeric(csc$OMENRAP8_FTNFT_POOLED_SUPP)
csc$OMENRUP8_FTNFT_POOLED_SUPP <- as.numeric(csc$OMENRUP8_FTNFT_POOLED_SUPP)
csc$OMAWDP6_PTNFT_POOLED_SUPP <- as.numeric(csc$OMAWDP6_PTNFT_POOLED_SUPP)
csc$OMAWDP8_PTNFT_POOLED_SUPP <- as.numeric(csc$OMAWDP8_PTNFT_POOLED_SUPP)
csc$OMENRYP8_PTNFT_POOLED_SUPP <- as.numeric(csc$OMENRYP8_PTNFT_POOLED_SUPP)
csc$OMENRAP8_PTNFT_POOLED_SUPP <- as.numeric(csc$OMENRAP8_PTNFT_POOLED_SUPP)
csc$OMENRUP8_PTNFT_POOLED_SUPP <- as.numeric(csc$OMENRUP8_PTNFT_POOLED_SUPP)
csc$SCHTYPE <- as.character(csc$SCHTYPE)
csc$OPEFLAG <- as.character(csc$OPEFLAG)
csc$PRGMOFR <- as.numeric(csc$PRGMOFR)
csc$CIPCODE1 <- as.character(csc$CIPCODE1)
csc$CIPCODE2 <- as.character(csc$CIPCODE2)
csc$CIPCODE3 <- as.character(csc$CIPCODE3)
csc$CIPCODE4 <- as.character(csc$CIPCODE4)
csc$CIPCODE5 <- as.character(csc$CIPCODE5)
csc$CIPCODE6 <- as.character(csc$CIPCODE6)
csc$CIPTITLE1 <- as.character(csc$CIPTITLE1)
csc$CIPTITLE2 <- as.character(csc$CIPTITLE2)
csc$CIPTITLE3 <- as.character(csc$CIPTITLE3)
csc$CIPTITLE4 <- as.character(csc$CIPTITLE4)
csc$CIPTITLE5 <- as.character(csc$CIPTITLE5)
csc$CIPTITLE6 <- as.character(csc$CIPTITLE6)
csc$CIPTFBS1 <- as.numeric(csc$CIPTFBS1)
csc$CIPTFBS2 <- as.numeric(csc$CIPTFBS2)
csc$CIPTFBS3 <- as.numeric(csc$CIPTFBS3)
csc$CIPTFBS4 <- as.numeric(csc$CIPTFBS4)
csc$CIPTFBS5 <- as.numeric(csc$CIPTFBS5)
csc$CIPTFBS6 <- as.numeric(csc$CIPTFBS6)
csc$CIPTFBSANNUAL1 <- as.numeric(csc$CIPTFBSANNUAL1)
csc$CIPTFBSANNUAL2 <- as.numeric(csc$CIPTFBSANNUAL2)
csc$CIPTFBSANNUAL3 <- as.numeric(csc$CIPTFBSANNUAL3)
csc$CIPTFBSANNUAL4 <- as.numeric(csc$CIPTFBSANNUAL4)
csc$CIPTFBSANNUAL5 <- as.numeric(csc$CIPTFBSANNUAL5)
csc$CIPTFBSANNUAL6 <- as.character(csc$CIPTFBSANNUAL6)
csc$MTHCMP1 <- as.numeric(csc$MTHCMP1)
csc$MTHCMP2 <- as.numeric(csc$MTHCMP2)
csc$MTHCMP3 <- as.numeric(csc$MTHCMP3)
csc$MTHCMP4 <- as.numeric(csc$MTHCMP4)
csc$MTHCMP5 <- as.numeric(csc$MTHCMP5)
csc$MTHCMP6 <- as.numeric(csc$MTHCMP6)
csc$POOLYRSOM_ALL <- as.numeric(csc$POOLYRSOM_ALL)
csc$POOLYRSOM_FIRSTTIME <- as.numeric(csc$POOLYRSOM_FIRSTTIME)
csc$POOLYRSOM_NOTFIRSTTIME <- as.numeric(csc$POOLYRSOM_NOTFIRSTTIME)
csc$POOLYRSOM_FULLTIME <- as.numeric(csc$POOLYRSOM_FULLTIME)
csc$POOLYRSOM_PARTTIME <- as.numeric(csc$POOLYRSOM_PARTTIME)
csc$OMENRYP_ALL <- as.numeric(csc$OMENRYP_ALL)
csc$OMENRAP_ALL <- as.numeric(csc$OMENRAP_ALL)
csc$OMAWDP8_ALL <- as.numeric(csc$OMAWDP8_ALL)
csc$OMENRUP_ALL <- as.numeric(csc$OMENRUP_ALL)
csc$OMENRYP_FIRSTTIME <- as.numeric(csc$OMENRYP_FIRSTTIME)
csc$OMENRAP_FIRSTTIME <- as.numeric(csc$OMENRAP_FIRSTTIME)
csc$OMAWDP8_FIRSTTIME <- as.numeric(csc$OMAWDP8_FIRSTTIME)
csc$OMENRUP_FIRSTTIME <- as.numeric(csc$OMENRUP_FIRSTTIME)
csc$OMENRYP_NOTFIRSTTIME <- as.numeric(csc$OMENRYP_NOTFIRSTTIME)
csc$OMENRAP_NOTFIRSTTIME <- as.numeric(csc$OMENRAP_NOTFIRSTTIME)
csc$OMAWDP8_NOTFIRSTTIME <- as.numeric(csc$OMAWDP8_NOTFIRSTTIME)
csc$OMENRUP_NOTFIRSTTIME <- as.numeric(csc$OMENRUP_NOTFIRSTTIME)
csc$OMENRYP_FULLTIME <- as.numeric(csc$OMENRYP_FULLTIME)
csc$OMENRAP_FULLTIME <- as.numeric(csc$OMENRAP_FULLTIME)
csc$OMAWDP8_FULLTIME <- as.numeric(csc$OMAWDP8_FULLTIME)
csc$OMENRUP_FULLTIME <- as.numeric(csc$OMENRUP_FULLTIME)
csc$OMENRYP_PARTTIME <- as.numeric(csc$OMENRYP_PARTTIME)
csc$OMENRAP_PARTTIME <- as.numeric(csc$OMENRAP_PARTTIME)
csc$OMAWDP8_PARTTIME <- as.numeric(csc$OMAWDP8_PARTTIME)
csc$OMENRUP_PARTTIME <- as.numeric(csc$OMENRUP_PARTTIME)
csc$OMENRYP_ALL_POOLED_SUPP <- as.numeric(csc$OMENRYP_ALL_POOLED_SUPP)
csc$OMENRAP_ALL_POOLED_SUPP <- as.numeric(csc$OMENRAP_ALL_POOLED_SUPP)
csc$OMAWDP8_ALL_POOLED_SUPP <- as.numeric(csc$OMAWDP8_ALL_POOLED_SUPP)
csc$OMENRUP_ALL_POOLED_SUPP <- as.numeric(csc$OMENRUP_ALL_POOLED_SUPP)
csc$OMENRYP_FIRSTTIME_POOLED_SUPP <- as.numeric(csc$OMENRYP_FIRSTTIME_POOLED_SUPP)
csc$OMENRAP_FIRSTTIME_POOLED_SUPP <- as.numeric(csc$OMENRAP_FIRSTTIME_POOLED_SUPP)
csc$OMAWDP8_FIRSTTIME_POOLED_SUPP <- as.numeric(csc$OMAWDP8_FIRSTTIME_POOLED_SUPP)
csc$OMENRUP_FIRSTTIME_POOLED_SUPP <- as.numeric(csc$OMENRUP_FIRSTTIME_POOLED_SUPP)
csc$OMENRYP_NOTFIRSTTIME_POOLED_SUPP <- as.numeric(csc$OMENRYP_NOTFIRSTTIME_POOLED_SUPP)
csc$OMENRAP_NOTFIRSTTIME_POOLED_SUPP <- as.numeric(csc$OMENRAP_NOTFIRSTTIME_POOLED_SUPP)
csc$OMAWDP8_NOTFIRSTTIME_POOLED_SUPP <- as.numeric(csc$OMAWDP8_NOTFIRSTTIME_POOLED_SUPP)
csc$OMENRUP_NOTFIRSTTIME_POOLED_SUPP <- as.numeric(csc$OMENRUP_NOTFIRSTTIME_POOLED_SUPP)
csc$OMENRYP_FULLTIME_POOLED_SUPP <- as.numeric(csc$OMENRYP_FULLTIME_POOLED_SUPP)
csc$OMENRAP_FULLTIME_POOLED_SUPP <- as.numeric(csc$OMENRAP_FULLTIME_POOLED_SUPP)
csc$OMAWDP8_FULLTIME_POOLED_SUPP <- as.numeric(csc$OMAWDP8_FULLTIME_POOLED_SUPP)
csc$OMENRUP_FULLTIME_POOLED_SUPP <- as.numeric(csc$OMENRUP_FULLTIME_POOLED_SUPP)
csc$OMENRYP_PARTTIME_POOLED_SUPP <- as.numeric(csc$OMENRYP_PARTTIME_POOLED_SUPP)
csc$OMENRAP_PARTTIME_POOLED_SUPP <- as.numeric(csc$OMENRAP_PARTTIME_POOLED_SUPP)
csc$OMAWDP8_PARTTIME_POOLED_SUPP <- as.numeric(csc$OMAWDP8_PARTTIME_POOLED_SUPP)
csc$OMENRUP_PARTTIME_POOLED_SUPP <- as.numeric(csc$OMENRUP_PARTTIME_POOLED_SUPP)
csc$FTFTPCTPELL <- as.numeric(csc$FTFTPCTPELL)
csc$FTFTPCTFLOAN <- as.numeric(csc$FTFTPCTFLOAN)
csc$UG12MN <- as.numeric(csc$UG12MN)
csc$G12MN <- as.numeric(csc$G12MN)
csc$SCUGFFN <- as.numeric(csc$SCUGFFN)
csc$POOLYRS_FTFTAIDPCT <- as.numeric(csc$POOLYRS_FTFTAIDPCT)
csc$FTFTPCTPELL_POOLED_SUPP <- as.numeric(csc$FTFTPCTPELL_POOLED_SUPP)
csc$FTFTPCTFLOAN_POOLED_SUPP <- as.numeric(csc$FTFTPCTFLOAN_POOLED_SUPP)
csc$SCUGFFN_POOLED <- as.numeric(csc$SCUGFFN_POOLED)
csc$PPLUS_PCT_LOW <- as.numeric(csc$PPLUS_PCT_LOW)
csc$PPLUS_PCT_HIGH <- as.numeric(csc$PPLUS_PCT_HIGH)
csc$PPLUS_PCT_LOW_POOLED_SUPP <- as.numeric(csc$PPLUS_PCT_LOW_POOLED_SUPP)
csc$PPLUS_PCT_HIGH_POOLED_SUPP <- as.numeric(csc$PPLUS_PCT_HIGH_POOLED_SUPP)
csc$POOLYRS_PLUSPCT <- as.numeric(csc$POOLYRS_PLUSPCT)
csc$PLUS_DEBT_INST_N <- as.numeric(csc$PLUS_DEBT_INST_N)
csc$PLUS_DEBT_INST_MD <- as.numeric(csc$PLUS_DEBT_INST_MD)
csc$PLUS_DEBT_ALL_N <- as.numeric(csc$PLUS_DEBT_ALL_N)
csc$PLUS_DEBT_ALL_MD <- as.numeric(csc$PLUS_DEBT_ALL_MD)
csc$PLUS_DEBT_INST_COMP_N <- as.numeric(csc$PLUS_DEBT_INST_COMP_N)
csc$PLUS_DEBT_INST_COMP_MD <- as.numeric(csc$PLUS_DEBT_INST_COMP_MD)
csc$PLUS_DEBT_INST_COMP_MDPAY10 <- as.numeric(csc$PLUS_DEBT_INST_COMP_MDPAY10)
csc$PLUS_DEBT_INST_COMP_MD_SUPP <- as.numeric(csc$PLUS_DEBT_INST_COMP_MD_SUPP)
csc$PLUS_DEBT_INST_COMP_MDPAY10_SUPP <- as.numeric(csc$PLUS_DEBT_INST_COMP_MDPAY10_SUPP)
csc$PLUS_DEBT_ALL_COMP_N <- as.numeric(csc$PLUS_DEBT_ALL_COMP_N)
csc$PLUS_DEBT_ALL_COMP_MD <- as.numeric(csc$PLUS_DEBT_ALL_COMP_MD)
csc$PLUS_DEBT_ALL_COMP_MDPAY10 <- as.numeric(csc$PLUS_DEBT_ALL_COMP_MDPAY10)
csc$PLUS_DEBT_ALL_COMP_MD_SUPP <- as.numeric(csc$PLUS_DEBT_ALL_COMP_MD_SUPP)
csc$PLUS_DEBT_ALL_COMP_MDPAY10_SUPP <- as.numeric(csc$PLUS_DEBT_ALL_COMP_MDPAY10_SUPP)
csc$PLUS_DEBT_INST_NOCOMP_N <- as.numeric(csc$PLUS_DEBT_INST_NOCOMP_N)
csc$PLUS_DEBT_INST_NOCOMP_MD <- as.numeric(csc$PLUS_DEBT_INST_NOCOMP_MD)
csc$PLUS_DEBT_ALL_NOCOMP_N <- as.numeric(csc$PLUS_DEBT_ALL_NOCOMP_N)
csc$PLUS_DEBT_ALL_NOCOMP_MD <- as.numeric(csc$PLUS_DEBT_ALL_NOCOMP_MD)
csc$PLUS_DEBT_INST_MALE_N <- as.numeric(csc$PLUS_DEBT_INST_MALE_N)
csc$PLUS_DEBT_INST_MALE_MD <- as.numeric(csc$PLUS_DEBT_INST_MALE_MD)
csc$PLUS_DEBT_ALL_MALE_N <- as.numeric(csc$PLUS_DEBT_ALL_MALE_N)
csc$PLUS_DEBT_ALL_MALE_MD <- as.numeric(csc$PLUS_DEBT_ALL_MALE_MD)
csc$PLUS_DEBT_INST_NOMALE_N <- as.numeric(csc$PLUS_DEBT_INST_NOMALE_N)
csc$PLUS_DEBT_INST_NOMALE_MD <- as.numeric(csc$PLUS_DEBT_INST_NOMALE_MD)
csc$PLUS_DEBT_ALL_NOMALE_N <- as.numeric(csc$PLUS_DEBT_ALL_NOMALE_N)
csc$PLUS_DEBT_ALL_NOMALE_MD <- as.numeric(csc$PLUS_DEBT_ALL_NOMALE_MD)
csc$PLUS_DEBT_INST_PELL_N <- as.numeric(csc$PLUS_DEBT_INST_PELL_N)
csc$PLUS_DEBT_INST_PELL_MD <- as.numeric(csc$PLUS_DEBT_INST_PELL_MD)
csc$PLUS_DEBT_ALL_PELL_N <- as.numeric(csc$PLUS_DEBT_ALL_PELL_N)
csc$PLUS_DEBT_ALL_PELL_MD <- as.numeric(csc$PLUS_DEBT_ALL_PELL_MD)
csc$PLUS_DEBT_INST_NOPELL_N <- as.numeric(csc$PLUS_DEBT_INST_NOPELL_N)
csc$PLUS_DEBT_INST_NOPELL_MD <- as.numeric(csc$PLUS_DEBT_INST_NOPELL_MD)
csc$PLUS_DEBT_ALL_NOPELL_N <- as.numeric(csc$PLUS_DEBT_ALL_NOPELL_N)
csc$PLUS_DEBT_ALL_NOPELL_MD <- as.numeric(csc$PLUS_DEBT_ALL_NOPELL_MD)
csc$PLUS_DEBT_INST_STAFFTHIS_N <- as.numeric(csc$PLUS_DEBT_INST_STAFFTHIS_N)
csc$PLUS_DEBT_INST_STAFFTHIS_MD <- as.numeric(csc$PLUS_DEBT_INST_STAFFTHIS_MD)
csc$PLUS_DEBT_ALL_STAFFTHIS_N <- as.numeric(csc$PLUS_DEBT_ALL_STAFFTHIS_N)
csc$PLUS_DEBT_ALL_STAFFTHIS_MD <- as.numeric(csc$PLUS_DEBT_ALL_STAFFTHIS_MD)
csc$PLUS_DEBT_INST_NOSTAFFTHIS_N <- as.numeric(csc$PLUS_DEBT_INST_NOSTAFFTHIS_N)
csc$PLUS_DEBT_INST_NOSTAFFTHIS_MD <- as.numeric(csc$PLUS_DEBT_INST_NOSTAFFTHIS_MD)
csc$PLUS_DEBT_ALL_NOSTAFFTHIS_N <- as.numeric(csc$PLUS_DEBT_ALL_NOSTAFFTHIS_N)
csc$PLUS_DEBT_ALL_NOSTAFFTHIS_MD <- as.numeric(csc$PLUS_DEBT_ALL_NOSTAFFTHIS_MD)
csc$PLUS_DEBT_INST_STAFFANY_N <- as.numeric(csc$PLUS_DEBT_INST_STAFFANY_N)
csc$PLUS_DEBT_INST_STAFFANY_MD <- as.numeric(csc$PLUS_DEBT_INST_STAFFANY_MD)
csc$PLUS_DEBT_ALL_STAFFANY_N <- as.numeric(csc$PLUS_DEBT_ALL_STAFFANY_N)
csc$PLUS_DEBT_ALL_STAFFANY_MD <- as.numeric(csc$PLUS_DEBT_ALL_STAFFANY_MD)
csc$PLUS_DEBT_INST_NOSTAFFANY_N <- as.numeric(csc$PLUS_DEBT_INST_NOSTAFFANY_N)
csc$PLUS_DEBT_INST_NOSTAFFANY_MD <- as.numeric(csc$PLUS_DEBT_INST_NOSTAFFANY_MD)
csc$PLUS_DEBT_ALL_NOSTAFFANY_N <- as.numeric(csc$PLUS_DEBT_ALL_NOSTAFFANY_N)
csc$PLUS_DEBT_ALL_NOSTAFFANY_MD <- as.numeric(csc$PLUS_DEBT_ALL_NOSTAFFANY_MD)
csc$DBRR1_FED_UG_N <- as.numeric(csc$DBRR1_FED_UG_N)
csc$DBRR1_FED_UG_NUM <- as.numeric(csc$DBRR1_FED_UG_NUM)
csc$DBRR1_FED_UG_DEN <- as.numeric(csc$DBRR1_FED_UG_DEN)
csc$DBRR1_FED_UG_RT <- as.numeric(csc$DBRR1_FED_UG_RT)
csc$DBRR1_FED_GR_N <- as.numeric(csc$DBRR1_FED_GR_N)
csc$DBRR1_FED_GR_NUM <- as.numeric(csc$DBRR1_FED_GR_NUM)
csc$DBRR1_FED_GR_DEN <- as.numeric(csc$DBRR1_FED_GR_DEN)
csc$DBRR1_FED_GR_RT <- as.numeric(csc$DBRR1_FED_GR_RT)
csc$DBRR1_FED_UGCOMP_N <- as.numeric(csc$DBRR1_FED_UGCOMP_N)
csc$DBRR1_FED_UGCOMP_NUM <- as.numeric(csc$DBRR1_FED_UGCOMP_NUM)
csc$DBRR1_FED_UGCOMP_DEN <- as.numeric(csc$DBRR1_FED_UGCOMP_DEN)
csc$DBRR1_FED_UGCOMP_RT <- as.numeric(csc$DBRR1_FED_UGCOMP_RT)
csc$DBRR1_FED_UGNOCOMP_N <- as.numeric(csc$DBRR1_FED_UGNOCOMP_N)
csc$DBRR1_FED_UGNOCOMP_NUM <- as.numeric(csc$DBRR1_FED_UGNOCOMP_NUM)
csc$DBRR1_FED_UGNOCOMP_DEN <- as.numeric(csc$DBRR1_FED_UGNOCOMP_DEN)
csc$DBRR1_FED_UGNOCOMP_RT <- as.numeric(csc$DBRR1_FED_UGNOCOMP_RT)
csc$DBRR1_FED_UGUNK_N <- as.numeric(csc$DBRR1_FED_UGUNK_N)
csc$DBRR1_FED_UGUNK_NUM <- as.numeric(csc$DBRR1_FED_UGUNK_NUM)
csc$DBRR1_FED_UGUNK_DEN <- as.numeric(csc$DBRR1_FED_UGUNK_DEN)
csc$DBRR1_FED_UGUNK_RT <- as.numeric(csc$DBRR1_FED_UGUNK_RT)
csc$DBRR1_FED_GRCOMP_N <- as.numeric(csc$DBRR1_FED_GRCOMP_N)
csc$DBRR1_FED_GRCOMP_NUM <- as.numeric(csc$DBRR1_FED_GRCOMP_NUM)
csc$DBRR1_FED_GRCOMP_DEN <- as.numeric(csc$DBRR1_FED_GRCOMP_DEN)
csc$DBRR1_FED_GRCOMP_RT <- as.numeric(csc$DBRR1_FED_GRCOMP_RT)
csc$DBRR1_FED_GRNOCOMP_N <- as.numeric(csc$DBRR1_FED_GRNOCOMP_N)
csc$DBRR1_FED_GRNOCOMP_NUM <- as.numeric(csc$DBRR1_FED_GRNOCOMP_NUM)
csc$DBRR1_FED_GRNOCOMP_DEN <- as.numeric(csc$DBRR1_FED_GRNOCOMP_DEN)
csc$DBRR1_FED_GRNOCOMP_RT <- as.numeric(csc$DBRR1_FED_GRNOCOMP_RT)
csc$DBRR4_FED_UG_N <- as.numeric(csc$DBRR4_FED_UG_N)
csc$DBRR4_FED_UG_NUM <- as.numeric(csc$DBRR4_FED_UG_NUM)
csc$DBRR4_FED_UG_DEN <- as.numeric(csc$DBRR4_FED_UG_DEN)
csc$DBRR4_FED_UG_RT <- as.numeric(csc$DBRR4_FED_UG_RT)
csc$DBRR4_FED_GR_N <- as.numeric(csc$DBRR4_FED_GR_N)
csc$DBRR4_FED_GR_NUM <- as.numeric(csc$DBRR4_FED_GR_NUM)
csc$DBRR4_FED_GR_DEN <- as.numeric(csc$DBRR4_FED_GR_DEN)
csc$DBRR4_FED_GR_RT <- as.numeric(csc$DBRR4_FED_GR_RT)
csc$DBRR4_FED_UGCOMP_N <- as.numeric(csc$DBRR4_FED_UGCOMP_N)
csc$DBRR4_FED_UGCOMP_NUM <- as.numeric(csc$DBRR4_FED_UGCOMP_NUM)
csc$DBRR4_FED_UGCOMP_DEN <- as.numeric(csc$DBRR4_FED_UGCOMP_DEN)
csc$DBRR4_FED_UGCOMP_RT <- as.numeric(csc$DBRR4_FED_UGCOMP_RT)
csc$DBRR4_FED_UGNOCOMP_N <- as.numeric(csc$DBRR4_FED_UGNOCOMP_N)
csc$DBRR4_FED_UGNOCOMP_NUM <- as.numeric(csc$DBRR4_FED_UGNOCOMP_NUM)
csc$DBRR4_FED_UGNOCOMP_DEN <- as.numeric(csc$DBRR4_FED_UGNOCOMP_DEN)
csc$DBRR4_FED_UGNOCOMP_RT <- as.numeric(csc$DBRR4_FED_UGNOCOMP_RT)
csc$DBRR4_FED_UGUNK_N <- as.numeric(csc$DBRR4_FED_UGUNK_N)
csc$DBRR4_FED_UGUNK_NUM <- as.numeric(csc$DBRR4_FED_UGUNK_NUM)
csc$DBRR4_FED_UGUNK_DEN <- as.numeric(csc$DBRR4_FED_UGUNK_DEN)
csc$DBRR4_FED_UGUNK_RT <- as.numeric(csc$DBRR4_FED_UGUNK_RT)
csc$DBRR5_FED_UG_N <- as.numeric(csc$DBRR5_FED_UG_N)
csc$DBRR5_FED_UG_NUM <- as.numeric(csc$DBRR5_FED_UG_NUM)
csc$DBRR5_FED_UG_DEN <- as.numeric(csc$DBRR5_FED_UG_DEN)
csc$DBRR5_FED_UG_RT <- as.numeric(csc$DBRR5_FED_UG_RT)
csc$DBRR5_FED_GR_N <- as.numeric(csc$DBRR5_FED_GR_N)
csc$DBRR5_FED_GR_NUM <- as.numeric(csc$DBRR5_FED_GR_NUM)
csc$DBRR5_FED_GR_DEN <- as.numeric(csc$DBRR5_FED_GR_DEN)
csc$DBRR5_FED_GR_RT <- as.numeric(csc$DBRR5_FED_GR_RT)
csc$DBRR10_FED_UG_N <- as.numeric(csc$DBRR10_FED_UG_N)
csc$DBRR10_FED_UG_NUM <- as.numeric(csc$DBRR10_FED_UG_NUM)
csc$DBRR10_FED_UG_DEN <- as.numeric(csc$DBRR10_FED_UG_DEN)
csc$DBRR10_FED_UG_RT <- as.numeric(csc$DBRR10_FED_UG_RT)
csc$DBRR10_FED_GR_N <- as.numeric(csc$DBRR10_FED_GR_N)
csc$DBRR10_FED_GR_NUM <- as.numeric(csc$DBRR10_FED_GR_NUM)
csc$DBRR10_FED_GR_DEN <- as.numeric(csc$DBRR10_FED_GR_DEN)
csc$DBRR10_FED_GR_RT <- as.numeric(csc$DBRR10_FED_GR_RT)
csc$DBRR20_FED_UG_N <- as.numeric(csc$DBRR20_FED_UG_N)
csc$DBRR20_FED_UG_NUM <- as.numeric(csc$DBRR20_FED_UG_NUM)
csc$DBRR20_FED_UG_DEN <- as.numeric(csc$DBRR20_FED_UG_DEN)
csc$DBRR20_FED_UG_RT <- as.numeric(csc$DBRR20_FED_UG_RT)
csc$DBRR20_FED_GR_N <- as.numeric(csc$DBRR20_FED_GR_N)
csc$DBRR20_FED_GR_NUM <- as.numeric(csc$DBRR20_FED_GR_NUM)
csc$DBRR20_FED_GR_DEN <- as.numeric(csc$DBRR20_FED_GR_DEN)
csc$DBRR20_FED_GR_RT <- as.numeric(csc$DBRR20_FED_GR_RT)
csc$DBRR1_PP_UG_N <- as.numeric(csc$DBRR1_PP_UG_N)
csc$DBRR1_PP_UG_NUM <- as.numeric(csc$DBRR1_PP_UG_NUM)
csc$DBRR1_PP_UG_DEN <- as.numeric(csc$DBRR1_PP_UG_DEN)
csc$DBRR1_PP_UG_RT <- as.numeric(csc$DBRR1_PP_UG_RT)
csc$DBRR1_PP_UGCOMP_N <- as.numeric(csc$DBRR1_PP_UGCOMP_N)
csc$DBRR1_PP_UGCOMP_NUM <- as.numeric(csc$DBRR1_PP_UGCOMP_NUM)
csc$DBRR1_PP_UGCOMP_DEN <- as.numeric(csc$DBRR1_PP_UGCOMP_DEN)
csc$DBRR1_PP_UGCOMP_RT <- as.numeric(csc$DBRR1_PP_UGCOMP_RT)
csc$DBRR1_PP_UGNOCOMP_N <- as.numeric(csc$DBRR1_PP_UGNOCOMP_N)
csc$DBRR1_PP_UGNOCOMP_NUM <- as.numeric(csc$DBRR1_PP_UGNOCOMP_NUM)
csc$DBRR1_PP_UGNOCOMP_DEN <- as.numeric(csc$DBRR1_PP_UGNOCOMP_DEN)
csc$DBRR1_PP_UGNOCOMP_RT <- as.numeric(csc$DBRR1_PP_UGNOCOMP_RT)
csc$DBRR1_PP_UGUNK_N <- as.numeric(csc$DBRR1_PP_UGUNK_N)
csc$DBRR1_PP_UGUNK_NUM <- as.numeric(csc$DBRR1_PP_UGUNK_NUM)
csc$DBRR1_PP_UGUNK_DEN <- as.numeric(csc$DBRR1_PP_UGUNK_DEN)
csc$DBRR1_PP_UGUNK_RT <- as.numeric(csc$DBRR1_PP_UGUNK_RT)
csc$DBRR4_PP_UG_N <- as.numeric(csc$DBRR4_PP_UG_N)
csc$DBRR4_PP_UG_NUM <- as.numeric(csc$DBRR4_PP_UG_NUM)
csc$DBRR4_PP_UG_DEN <- as.numeric(csc$DBRR4_PP_UG_DEN)
csc$DBRR4_PP_UG_RT <- as.numeric(csc$DBRR4_PP_UG_RT)
csc$DBRR4_PP_UGCOMP_N <- as.numeric(csc$DBRR4_PP_UGCOMP_N)
csc$DBRR4_PP_UGCOMP_NUM <- as.numeric(csc$DBRR4_PP_UGCOMP_NUM)
csc$DBRR4_PP_UGCOMP_DEN <- as.numeric(csc$DBRR4_PP_UGCOMP_DEN)
csc$DBRR4_PP_UGCOMP_RT <- as.numeric(csc$DBRR4_PP_UGCOMP_RT)
csc$DBRR4_PP_UGNOCOMP_N <- as.numeric(csc$DBRR4_PP_UGNOCOMP_N)
csc$DBRR4_PP_UGNOCOMP_NUM <- as.numeric(csc$DBRR4_PP_UGNOCOMP_NUM)
csc$DBRR4_PP_UGNOCOMP_DEN <- as.numeric(csc$DBRR4_PP_UGNOCOMP_DEN)
csc$DBRR4_PP_UGNOCOMP_RT <- as.numeric(csc$DBRR4_PP_UGNOCOMP_RT)
csc$DBRR4_PP_UGUNK_N <- as.numeric(csc$DBRR4_PP_UGUNK_N)
csc$DBRR4_PP_UGUNK_NUM <- as.numeric(csc$DBRR4_PP_UGUNK_NUM)
csc$DBRR4_PP_UGUNK_DEN <- as.numeric(csc$DBRR4_PP_UGUNK_DEN)
csc$DBRR4_PP_UGUNK_RT <- as.numeric(csc$DBRR4_PP_UGUNK_RT)
csc$DBRR5_PP_UG_N <- as.numeric(csc$DBRR5_PP_UG_N)
csc$DBRR5_PP_UG_NUM <- as.numeric(csc$DBRR5_PP_UG_NUM)
csc$DBRR5_PP_UG_DEN <- as.numeric(csc$DBRR5_PP_UG_DEN)
csc$DBRR5_PP_UG_RT <- as.numeric(csc$DBRR5_PP_UG_RT)
csc$DBRR10_PP_UG_N <- as.numeric(csc$DBRR10_PP_UG_N)
csc$DBRR10_PP_UG_NUM <- as.numeric(csc$DBRR10_PP_UG_NUM)
csc$DBRR10_PP_UG_DEN <- as.numeric(csc$DBRR10_PP_UG_DEN)
csc$DBRR10_PP_UG_RT <- as.numeric(csc$DBRR10_PP_UG_RT)
csc$DBRR20_PP_UG_N <- as.numeric(csc$DBRR20_PP_UG_N)
csc$DBRR20_PP_UG_NUM <- as.numeric(csc$DBRR20_PP_UG_NUM)
csc$DBRR20_PP_UG_DEN <- as.numeric(csc$DBRR20_PP_UG_DEN)
csc$DBRR20_PP_UG_RT <- as.numeric(csc$DBRR20_PP_UG_RT)
csc$BBRR2_FED_UG_N <- as.numeric(csc$BBRR2_FED_UG_N)
csc$BBRR2_FED_UG_DFLT <- as.numeric(csc$BBRR2_FED_UG_DFLT)
csc$BBRR2_FED_UG_DLNQ <- as.numeric(csc$BBRR2_FED_UG_DLNQ)
csc$BBRR2_FED_UG_FBR <- as.numeric(csc$BBRR2_FED_UG_FBR)
csc$BBRR2_FED_UG_DFR <- as.numeric(csc$BBRR2_FED_UG_DFR)
csc$BBRR2_FED_UG_NOPROG <- as.numeric(csc$BBRR2_FED_UG_NOPROG)
csc$BBRR2_FED_UG_MAKEPROG <- as.numeric(csc$BBRR2_FED_UG_MAKEPROG)
csc$BBRR2_FED_UG_PAIDINFULL <- as.numeric(csc$BBRR2_FED_UG_PAIDINFULL)
csc$BBRR2_FED_UG_DISCHARGE <- as.numeric(csc$BBRR2_FED_UG_DISCHARGE)
csc$BBRR2_FED_UGCOMP_N <- as.numeric(csc$BBRR2_FED_UGCOMP_N)
csc$BBRR2_FED_UGCOMP_DFLT <- as.numeric(csc$BBRR2_FED_UGCOMP_DFLT)
csc$BBRR2_FED_UGCOMP_DLNQ <- as.numeric(csc$BBRR2_FED_UGCOMP_DLNQ)
csc$BBRR2_FED_UGCOMP_FBR <- as.numeric(csc$BBRR2_FED_UGCOMP_FBR)
csc$BBRR2_FED_UGCOMP_DFR <- as.numeric(csc$BBRR2_FED_UGCOMP_DFR)
csc$BBRR2_FED_UGCOMP_NOPROG <- as.numeric(csc$BBRR2_FED_UGCOMP_NOPROG)
csc$BBRR2_FED_UGCOMP_MAKEPROG <- as.numeric(csc$BBRR2_FED_UGCOMP_MAKEPROG)
csc$BBRR2_FED_UGCOMP_PAIDINFULL <- as.numeric(csc$BBRR2_FED_UGCOMP_PAIDINFULL)
csc$BBRR2_FED_UGCOMP_DISCHARGE <- as.numeric(csc$BBRR2_FED_UGCOMP_DISCHARGE)
csc$BBRR2_FED_UGNOCOMP_N <- as.numeric(csc$BBRR2_FED_UGNOCOMP_N)
csc$BBRR2_FED_UGNOCOMP_DFLT <- as.numeric(csc$BBRR2_FED_UGNOCOMP_DFLT)
csc$BBRR2_FED_UGNOCOMP_DLNQ <- as.numeric(csc$BBRR2_FED_UGNOCOMP_DLNQ)
csc$BBRR2_FED_UGNOCOMP_FBR <- as.numeric(csc$BBRR2_FED_UGNOCOMP_FBR)
csc$BBRR2_FED_UGNOCOMP_DFR <- as.numeric(csc$BBRR2_FED_UGNOCOMP_DFR)
csc$BBRR2_FED_UGNOCOMP_NOPROG <- as.numeric(csc$BBRR2_FED_UGNOCOMP_NOPROG)
csc$BBRR2_FED_UGNOCOMP_MAKEPROG <- as.numeric(csc$BBRR2_FED_UGNOCOMP_MAKEPROG)
csc$BBRR2_FED_UGNOCOMP_PAIDINFULL <- as.numeric(csc$BBRR2_FED_UGNOCOMP_PAIDINFULL)
csc$BBRR2_FED_UGNOCOMP_DISCHARGE <- as.numeric(csc$BBRR2_FED_UGNOCOMP_DISCHARGE)
csc$BBRR2_FED_UGUNK_N <- as.numeric(csc$BBRR2_FED_UGUNK_N)
csc$BBRR2_FED_UGUNK_DFLT <- as.numeric(csc$BBRR2_FED_UGUNK_DFLT)
csc$BBRR2_FED_UGUNK_DLNQ <- as.numeric(csc$BBRR2_FED_UGUNK_DLNQ)
csc$BBRR2_FED_UGUNK_FBR <- as.numeric(csc$BBRR2_FED_UGUNK_FBR)
csc$BBRR2_FED_UGUNK_DFR <- as.numeric(csc$BBRR2_FED_UGUNK_DFR)
csc$BBRR2_FED_UGUNK_NOPROG <- as.numeric(csc$BBRR2_FED_UGUNK_NOPROG)
csc$BBRR2_FED_UGUNK_MAKEPROG <- as.numeric(csc$BBRR2_FED_UGUNK_MAKEPROG)
csc$BBRR2_FED_UGUNK_PAIDINFULL <- as.numeric(csc$BBRR2_FED_UGUNK_PAIDINFULL)
csc$BBRR2_FED_UGUNK_DISCHARGE <- as.numeric(csc$BBRR2_FED_UGUNK_DISCHARGE)
csc$BBRR2_FED_GR_N <- as.numeric(csc$BBRR2_FED_GR_N)
csc$BBRR2_FED_GR_DFLT <- as.numeric(csc$BBRR2_FED_GR_DFLT)
csc$BBRR2_FED_GR_DLNQ <- as.numeric(csc$BBRR2_FED_GR_DLNQ)
csc$BBRR2_FED_GR_FBR <- as.numeric(csc$BBRR2_FED_GR_FBR)
csc$BBRR2_FED_GR_DFR <- as.numeric(csc$BBRR2_FED_GR_DFR)
csc$BBRR2_FED_GR_NOPROG <- as.numeric(csc$BBRR2_FED_GR_NOPROG)
csc$BBRR2_FED_GR_MAKEPROG <- as.numeric(csc$BBRR2_FED_GR_MAKEPROG)
csc$BBRR2_FED_GR_PAIDINFULL <- as.numeric(csc$BBRR2_FED_GR_PAIDINFULL)
csc$BBRR2_FED_GR_DISCHARGE <- as.numeric(csc$BBRR2_FED_GR_DISCHARGE)
csc$BBRR2_FED_GRCOMP_N <- as.numeric(csc$BBRR2_FED_GRCOMP_N)
csc$BBRR2_FED_GRCOMP_DFLT <- as.numeric(csc$BBRR2_FED_GRCOMP_DFLT)
csc$BBRR2_FED_GRCOMP_DLNQ <- as.numeric(csc$BBRR2_FED_GRCOMP_DLNQ)
csc$BBRR2_FED_GRCOMP_FBR <- as.numeric(csc$BBRR2_FED_GRCOMP_FBR)
csc$BBRR2_FED_GRCOMP_DFR <- as.numeric(csc$BBRR2_FED_GRCOMP_DFR)
csc$BBRR2_FED_GRCOMP_NOPROG <- as.numeric(csc$BBRR2_FED_GRCOMP_NOPROG)
csc$BBRR2_FED_GRCOMP_MAKEPROG <- as.numeric(csc$BBRR2_FED_GRCOMP_MAKEPROG)
csc$BBRR2_FED_GRCOMP_PAIDINFULL <- as.numeric(csc$BBRR2_FED_GRCOMP_PAIDINFULL)
csc$BBRR2_FED_GRCOMP_DISCHARGE <- as.numeric(csc$BBRR2_FED_GRCOMP_DISCHARGE)
csc$BBRR2_FED_GRNOCOMP_N <- as.numeric(csc$BBRR2_FED_GRNOCOMP_N)
csc$BBRR2_FED_GRNOCOMP_DFLT <- as.numeric(csc$BBRR2_FED_GRNOCOMP_DFLT)
csc$BBRR2_FED_GRNOCOMP_DLNQ <- as.numeric(csc$BBRR2_FED_GRNOCOMP_DLNQ)
csc$BBRR2_FED_GRNOCOMP_FBR <- as.numeric(csc$BBRR2_FED_GRNOCOMP_FBR)
csc$BBRR2_FED_GRNOCOMP_DFR <- as.numeric(csc$BBRR2_FED_GRNOCOMP_DFR)
csc$BBRR2_FED_GRNOCOMP_NOPROG <- as.numeric(csc$BBRR2_FED_GRNOCOMP_NOPROG)
csc$BBRR2_FED_GRNOCOMP_MAKEPROG <- as.numeric(csc$BBRR2_FED_GRNOCOMP_MAKEPROG)
csc$BBRR2_FED_GRNOCOMP_PAIDINFULL <- as.numeric(csc$BBRR2_FED_GRNOCOMP_PAIDINFULL)
csc$BBRR2_FED_GRNOCOMP_DISCHARGE <- as.numeric(csc$BBRR2_FED_GRNOCOMP_DISCHARGE)
csc$BBRR2_PP_UG_N <- as.numeric(csc$BBRR2_PP_UG_N)
csc$BBRR2_PP_UG_DFLT <- as.numeric(csc$BBRR2_PP_UG_DFLT)
csc$BBRR2_PP_UG_DLNQ <- as.numeric(csc$BBRR2_PP_UG_DLNQ)
csc$BBRR2_PP_UG_FBR <- as.numeric(csc$BBRR2_PP_UG_FBR)
csc$BBRR2_PP_UG_DFR <- as.numeric(csc$BBRR2_PP_UG_DFR)
csc$BBRR2_PP_UG_NOPROG <- as.numeric(csc$BBRR2_PP_UG_NOPROG)
csc$BBRR2_PP_UG_MAKEPROG <- as.numeric(csc$BBRR2_PP_UG_MAKEPROG)
csc$BBRR2_PP_UG_PAIDINFULL <- as.numeric(csc$BBRR2_PP_UG_PAIDINFULL)
csc$BBRR2_PP_UG_DISCHARGE <- as.numeric(csc$BBRR2_PP_UG_DISCHARGE)
csc$BBRR2_PP_UGCOMP_N <- as.numeric(csc$BBRR2_PP_UGCOMP_N)
csc$BBRR2_PP_UGCOMP_DFLT <- as.numeric(csc$BBRR2_PP_UGCOMP_DFLT)
csc$BBRR2_PP_UGCOMP_DLNQ <- as.numeric(csc$BBRR2_PP_UGCOMP_DLNQ)
csc$BBRR2_PP_UGCOMP_FBR <- as.numeric(csc$BBRR2_PP_UGCOMP_FBR)
csc$BBRR2_PP_UGCOMP_DFR <- as.numeric(csc$BBRR2_PP_UGCOMP_DFR)
csc$BBRR2_PP_UGCOMP_NOPROG <- as.numeric(csc$BBRR2_PP_UGCOMP_NOPROG)
csc$BBRR2_PP_UGCOMP_MAKEPROG <- as.numeric(csc$BBRR2_PP_UGCOMP_MAKEPROG)
csc$BBRR2_PP_UGCOMP_PAIDINFULL <- as.numeric(csc$BBRR2_PP_UGCOMP_PAIDINFULL)
csc$BBRR2_PP_UGCOMP_DISCHARGE <- as.numeric(csc$BBRR2_PP_UGCOMP_DISCHARGE)
csc$BBRR2_PP_UGNOCOMP_N <- as.numeric(csc$BBRR2_PP_UGNOCOMP_N)
csc$BBRR2_PP_UGNOCOMP_DFLT <- as.numeric(csc$BBRR2_PP_UGNOCOMP_DFLT)
csc$BBRR2_PP_UGNOCOMP_DLNQ <- as.numeric(csc$BBRR2_PP_UGNOCOMP_DLNQ)
csc$BBRR2_PP_UGNOCOMP_FBR <- as.numeric(csc$BBRR2_PP_UGNOCOMP_FBR)
csc$BBRR2_PP_UGNOCOMP_DFR <- as.numeric(csc$BBRR2_PP_UGNOCOMP_DFR)
csc$BBRR2_PP_UGNOCOMP_NOPROG <- as.numeric(csc$BBRR2_PP_UGNOCOMP_NOPROG)
csc$BBRR2_PP_UGNOCOMP_MAKEPROG <- as.numeric(csc$BBRR2_PP_UGNOCOMP_MAKEPROG)
csc$BBRR2_PP_UGNOCOMP_PAIDINFULL <- as.numeric(csc$BBRR2_PP_UGNOCOMP_PAIDINFULL)
csc$BBRR2_PP_UGNOCOMP_DISCHARGE <- as.numeric(csc$BBRR2_PP_UGNOCOMP_DISCHARGE)
csc$BBRR2_PP_UGUNK_N <- as.numeric(csc$BBRR2_PP_UGUNK_N)
csc$BBRR2_PP_UGUNK_DFLT <- as.numeric(csc$BBRR2_PP_UGUNK_DFLT)
#csc$BBRR2_PP_UGUNK_DLNQ <- as.numeric(csc$BBRR2_PP_UGUNK_DLNQ)
csc$BBRR2_PP_UGUNK_FBR <- as.numeric(csc$BBRR2_PP_UGUNK_FBR)
csc$BBRR2_PP_UGUNK_DFR <- as.numeric(csc$BBRR2_PP_UGUNK_DFR)
csc$BBRR2_PP_UGUNK_NOPROG <- as.numeric(csc$BBRR2_PP_UGUNK_NOPROG)
csc$BBRR2_PP_UGUNK_MAKEPROG <- as.numeric(csc$BBRR2_PP_UGUNK_MAKEPROG)
csc$BBRR2_PP_UGUNK_PAIDINFULL <- as.numeric(csc$BBRR2_PP_UGUNK_PAIDINFULL)
csc$BBRR2_PP_UGUNK_DISCHARGE <- as.numeric(csc$BBRR2_PP_UGUNK_DISCHARGE)
csc$BBRR2_FED_UG_N_SUPP <- as.numeric(csc$BBRR2_FED_UG_N_SUPP)
csc$BBRR2_FED_UG_DFLT_SUPP <- as.numeric(csc$BBRR2_FED_UG_DFLT_SUPP)
csc$BBRR2_FED_UG_DLNQ_SUPP <- as.numeric(csc$BBRR2_FED_UG_DLNQ_SUPP)
csc$BBRR2_FED_UG_FBR_SUPP <- as.numeric(csc$BBRR2_FED_UG_FBR_SUPP)
csc$BBRR2_FED_UG_DFR_SUPP <- as.numeric(csc$BBRR2_FED_UG_DFR_SUPP)
csc$BBRR2_FED_UG_NOPROG_SUPP <- as.numeric(csc$BBRR2_FED_UG_NOPROG_SUPP)
csc$BBRR2_FED_UG_MAKEPROG_SUPP <- as.numeric(csc$BBRR2_FED_UG_MAKEPROG_SUPP)
csc$BBRR2_FED_UG_PAIDINFULL_SUPP <- as.numeric(csc$BBRR2_FED_UG_PAIDINFULL_SUPP)
csc$BBRR2_FED_UG_DISCHARGE_SUPP <- as.numeric(csc$BBRR2_FED_UG_DISCHARGE_SUPP)
csc$BBRR2_FED_UGCOMP_N_SUPP <- as.numeric(csc$BBRR2_FED_UGCOMP_N_SUPP)
csc$BBRR2_FED_UGCOMP_DFLT_SUPP <- as.numeric(csc$BBRR2_FED_UGCOMP_DFLT_SUPP)
csc$BBRR2_FED_UGCOMP_DLNQ_SUPP <- as.numeric(csc$BBRR2_FED_UGCOMP_DLNQ_SUPP)
csc$BBRR2_FED_UGCOMP_FBR_SUPP <- as.numeric(csc$BBRR2_FED_UGCOMP_FBR_SUPP)
csc$BBRR2_FED_UGCOMP_DFR_SUPP <- as.numeric(csc$BBRR2_FED_UGCOMP_DFR_SUPP)
csc$BBRR2_FED_UGCOMP_NOPROG_SUPP <- as.numeric(csc$BBRR2_FED_UGCOMP_NOPROG_SUPP)
csc$BBRR2_FED_UGCOMP_MAKEPROG_SUPP <- as.numeric(csc$BBRR2_FED_UGCOMP_MAKEPROG_SUPP)
csc$BBRR2_FED_UGCOMP_PAIDINFULL_SUPP <- as.numeric(csc$BBRR2_FED_UGCOMP_PAIDINFULL_SUPP)
csc$BBRR2_FED_UGCOMP_DISCHARGE_SUPP <- as.numeric(csc$BBRR2_FED_UGCOMP_DISCHARGE_SUPP)
csc$LPSTAFFORD_CNT <- as.numeric(csc$LPSTAFFORD_CNT)
csc$LPSTAFFORD_AMT <- as.numeric(csc$LPSTAFFORD_AMT)
csc$LPPPLUS_CNT <- as.numeric(csc$LPPPLUS_CNT)
csc$LPPPLUS_AMT <- as.numeric(csc$LPPPLUS_AMT)
csc$LPGPLUS_CNT <- as.numeric(csc$LPGPLUS_CNT)
csc$LPGPLUS_AMT <- as.numeric(csc$LPGPLUS_AMT)
csc$FEDSCHCD <- as.character(csc$FEDSCHCD)

csc %<>% filter(!is.na(LONGITUDE)) %>%
         filter(!is.na(LATITUDE))

# nms <- see_missing(csc) %>%
#     mutate(nmiss = max(Count) - Count,
#            pct = Count / max(Count), 
#            pctmiss = nmiss / max(Count)) %>%
#     filter(Count > 0) %>%
#     select(Variable)


# csc %>% 
#     filter(OMENRYP_ALL > .125)


get_description <- function(df) {
    d1 <- as_tibble(lapply(df, function(x) sum(!is.na(x)))) %>%
            pivot_longer(cols = everything(),
                         names_to = "Variable", values_to = "n") %>%
            mutate(nmiss = max(n) - n, 
                   pctn = n / max(n), 
                   pctmiss = nmiss / max(n))
    d2 <- as_tibble(lapply(df, function(x) median(x, na.rm = T))) %>%
            pivot_longer(cols = everything(),
                         names_to = "Variable", values_to = "median")
    d3 <- as_tibble(lapply(df, function(x) mean(x, na.rm = T))) %>%
            pivot_longer(cols = everything(),
                         names_to = "Variable", values_to = "mean")
    d4 <- as_tibble(lapply(df, function(x) quantile(x, 1/4, na.rm = T))) %>%
            pivot_longer(cols = everything(),
                         names_to = "Variable", values_to = "Q1")
    d5 <- as_tibble(lapply(df, function(x) quantile(x, 3/4, na.rm = T))) %>%
            pivot_longer(cols = everything(),
                         names_to = "Variable", values_to = "Q3")

    left_join(d1,
              left_join(d2,
                        left_join(d3,
                                  left_join(d4, d5, by = "Variable"),
                                  by = "Variable"),
                        by = "Variable"),
              by = "Variable")
                            }

csc_data <- csc %>%
                filter(!is.na(PELLCAT)) %>%
                mutate(CONTROL2 = case_when(CONTROL == "1" ~ "Public",
                                            CONTROL == "2" ~ "Private",
                                            CONTROL == "3" ~ "Private"),
                       ICLEVEL2 = case_when(ICLEVEL == "1" ~ "4-year",
                                            ICLEVEL == "2" ~ "2-year",
                                            ICLEVEL == "3" ~ "2-year"),
                       PELLCAT2 = case_when(PELLCAT == 0 ~ "0 Minority Pell",
                                           PELLCAT == 1 ~ "1 Majority Pell"),
                       CONTROL_ICLEVEL = paste0(CONTROL2, " ", ICLEVEL2),
                       DEPPLUS_DEBT_MDN = DEP_DEBT_MDN + PLUS_DEBT_INST_MD,
                       GRAD_CAT = ifelse(is.na(OMAWDP8_ALL), NA,
                                         ifelse(OMAWDP8_ALL > 0.75, 3,
                                                ifelse(OMAWDP8_ALL > 0.50, 2,
                                                       ifelse(OMAWDP8_ALL <= 0.25, 0, 1)))))


bas <- c("UNITID", "INSTNM", "PELLCAT2", "CONTROL2", "ICLEVEL2", "CONTROL_ICLEVEL", "LONGITUDE", "LATITUDE", "BBRR2_FED_UG_N", "PCTFLOAN")

G_CE_T_U_rate <- c("OMAWDP8_ALL", "OMENRYP_ALL", "OMENRAP_ALL", "OMENRUP_ALL")
debt_variables <- c("DEBT_MDN", "IND_DEBT_MDN", "DEP_DEBT_MDN", 
                    "PLUS_DEBT_INST_MD", "PLUS_DEBT_INST_PELL_MD", "PLUS_DEBT_INST_NOPELL_MD",
                    "PLUS_DEBT_INST_COMP_MD", "PLUS_DEBT_INST_NOCOMP_MD",
                    "LO_INC_DEBT_MDN", "MD_INC_DEBT_MDN", "HI_INC_DEBT_MDN", 
                    "FIRSTGEN_DEBT_MDN", "NOTFIRSTGEN_DEBT_MDN", 
                    "PELL_DEBT_MDN", "NOPELL_DEBT_MDN", 
                    "GRAD_DEBT_MDN", "WDRAW_DEBT_MDN",
                    "PPLUS_PCT_LOW", "PPLUS_PCT_HIGH")
UG_loan_2yrs <- c("BBRR2_FED_UG_DFLT", "BBRR2_FED_UG_DLNQ", "BBRR2_FED_UG_FBR", "BBRR2_FED_UG_DFR", "BBRR2_FED_UG_NOPROG", "BBRR2_FED_UG_MAKEPROG", "BBRR2_FED_UG_PAIDINFULL", "BBRR2_FED_UG_DISCHARGE")
UGCOMP_loan_2yrs <- c("BBRR2_FED_UGCOMP_DFLT", "BBRR2_FED_UGCOMP_DLNQ", "BBRR2_FED_UGCOMP_FBR", "BBRR2_FED_UGCOMP_DFR", "BBRR2_FED_UGCOMP_NOPROG", "BBRR2_FED_UGCOMP_MAKEPROG", "BBRR2_FED_UGCOMP_PAIDINFULL", "BBRR2_FED_UGCOMP_DISCHARGE")
UGNOCOMP_loan_2yrs <- c("BBRR2_FED_UGNOCOMP_DFLT", "BBRR2_FED_UGNOCOMP_DLNQ", "BBRR2_FED_UGNOCOMP_FBR", "BBRR2_FED_UGNOCOMP_DFR", "BBRR2_FED_UGNOCOMP_NOPROG", "BBRR2_FED_UGNOCOMP_MAKEPROG", "BBRR2_FED_UGNOCOMP_PAIDINFULL", "BBRR2_FED_UGNOCOMP_DISCHARGE")

GCETU_rate <- csc_data %>% 
    select(all_of(bas), all_of(G_CE_T_U_rate)
           ) %>%
    mutate(onehundred = OMAWDP8_ALL + # Percentage of all student receiving an award within 8 years of entry
                         OMENRYP_ALL + # Percentage of all students that did not receive an award and are still enrolled at this institution 8 years after entry
                         OMENRAP_ALL + # Percentage of all students that did not receive an award and enrolled at another institution after leaving this institution within 8 years of entry
                         OMENRUP_ALL   # Percentage of all students that did not receive an award and whose enrollment status is unknown after leaving this institution within 8 years of entry
          )

UGLOAN2yr <- csc_data %>% 
    select(all_of(bas), all_of(UG_loan_2yrs)
           ) %>%
    mutate(onehundred = BBRR2_FED_UG_DFLT + # Percentage of graduate federal student loan borrowers in default after 2 years
                        BBRR2_FED_UG_DLNQ + # Percentage of graduate federal student loan borrowers in delinquency after 2 years
                        BBRR2_FED_UG_FBR + # Percentage of graduate federal student loan borrowers in forbearance after 2 years
                        BBRR2_FED_UG_DFR + # Percentage of graduate federal student loan borrowers in deferment after 2 years
                        BBRR2_FED_UG_NOPROG + # Percentage of graduate federal student loan borrowers not making progress after 2 years
                        BBRR2_FED_UG_MAKEPROG + # Percentage of graduate federal student loan borrowers making progress after 2 years
                        BBRR2_FED_UG_PAIDINFULL + # Percentage of graduate federal student loan borrowers paid in full after 2 years
                        BBRR2_FED_UG_DISCHARGE, # Percentage of graduate federal student loan borrowers with all loans discharged after 2 years
                        BBRR2_FED_UG_DFLT_DLNQ_FBR_DFR_NOPROG = BBRR2_FED_UG_DFLT + BBRR2_FED_UG_DLNQ + BBRR2_FED_UG_FBR + BBRR2_FED_UG_DFR + BBRR2_FED_UG_NOPROG,
                        NUM_BBRR2_FED_UG_DFLT = BBRR2_FED_UG_DFLT * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UG_DLNQ = BBRR2_FED_UG_DLNQ * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UG_FBR = BBRR2_FED_UG_FBR * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UG_DFR = BBRR2_FED_UG_DFR * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UG_NOPROG = BBRR2_FED_UG_NOPROG * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UG_MAKEPROG = BBRR2_FED_UG_MAKEPROG * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UG_PAIDINFULL = BBRR2_FED_UG_PAIDINFULL * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UG_DISCHARGE = BBRR2_FED_UG_DISCHARGE * BBRR2_FED_UG_N
          )
UGCOMPloan2yrs <- csc_data %>% 
    select(all_of(bas), all_of(UGCOMP_loan_2yrs)
           ) %>%
    mutate(onehundred = BBRR2_FED_UGCOMP_DFLT + # Percentage of graduate completer graduate federal student loan borrowers in default after 2 years
                        BBRR2_FED_UGCOMP_DLNQ + # Percentage of graduate completer graduate federal student loan borrowers in delinquency after 2 years
                        BBRR2_FED_UGCOMP_FBR + # Percentage of graduate completer graduate federal student loan borrowers in forbearance after 2 years
                        BBRR2_FED_UGCOMP_DFR + # Percentage of graduate completer graduate federal student loan borrowers in deferment after 2 years
                        BBRR2_FED_UGCOMP_NOPROG + # Percentage of graduate completer graduate federal student loan borrowers not making progress after 2 years
                        BBRR2_FED_UGCOMP_MAKEPROG + # Percentage of graduate completer graduate federal student loan borrowers making progress after 2 years
                        BBRR2_FED_UGCOMP_PAIDINFULL + # Percentage of graduate completer graduate federal student loan borrowers paid in full after 2 years
                        BBRR2_FED_UGCOMP_DISCHARGE, # Percentage of graduate completer graduate federal student loan borrowers with all loans discharged after 2 years
                        BBRR2_FED_UGCOMP_DFLT_DLNQ_FBR_DFR_NOPROG = BBRR2_FED_UGCOMP_DFLT + BBRR2_FED_UGCOMP_DLNQ + BBRR2_FED_UGCOMP_FBR + BBRR2_FED_UGCOMP_DFR + BBRR2_FED_UGCOMP_NOPROG,
                        NUM_BBRR2_FED_UGCOMP_DFLT = BBRR2_FED_UGCOMP_DFLT * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGCOMP_DLNQ = BBRR2_FED_UGCOMP_DLNQ * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGCOMP_FBR = BBRR2_FED_UGCOMP_FBR * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGCOMP_DFR = BBRR2_FED_UGCOMP_DFR * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGCOMP_NOPROG = BBRR2_FED_UGCOMP_NOPROG * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGCOMP_MAKEPROG = BBRR2_FED_UGCOMP_MAKEPROG * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGCOMP_PAIDINFULL = BBRR2_FED_UGCOMP_PAIDINFULL * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGCOMP_DISCHARGE = BBRR2_FED_UGCOMP_DISCHARGE * BBRR2_FED_UG_N
          )

UGNOCOMPloan2yrs <- csc_data %>% 
    select(all_of(bas), all_of(UGNOCOMP_loan_2yrs)
           ) %>%
    mutate(onehundred = BBRR2_FED_UGNOCOMP_DFLT + # Percentage of graduate non-completer graduate federal student loan borrowers in default after 2 years
                        BBRR2_FED_UGNOCOMP_DLNQ + # Percentage of graduate non-completer graduate federal student loan borrowers in delinquency after 2 years
                        BBRR2_FED_UGNOCOMP_FBR + # Percentage of graduate non-completer graduate federal student loan borrowers in forbearance after 2 years
                        BBRR2_FED_UGNOCOMP_DFR + # Percentage of graduate non-completer graduate federal student loan borrowers in deferment after 2 years
                        BBRR2_FED_UGNOCOMP_NOPROG + # Percentage of graduate non-completer graduate federal student loan borrowers not making progress after 2 years
                        BBRR2_FED_UGNOCOMP_MAKEPROG + # Percentage of graduate non-completer graduate federal student loan borrowers making progress after 2 years
                        BBRR2_FED_UGNOCOMP_PAIDINFULL + # Percentage of graduate non-completer graduate federal student loan borrowers paid in full after 2 years
                        BBRR2_FED_UGNOCOMP_DISCHARGE, # Percentage of graduate non-completer graduate federal student loan borrowers with all loans discharged after 2 years
                        BBRR2_FED_UGNOCOMP_DFLT_DLNQ_FBR_DFR_NOPROG = BBRR2_FED_UGNOCOMP_DFLT + BBRR2_FED_UGNOCOMP_DLNQ + BBRR2_FED_UGNOCOMP_FBR + BBRR2_FED_UGNOCOMP_DFR + BBRR2_FED_UGNOCOMP_NOPROG,
                        NUM_BBRR2_FED_UGNOCOMP_DFLT = BBRR2_FED_UGNOCOMP_DFLT * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGNOCOMP_DLNQ = BBRR2_FED_UGNOCOMP_DLNQ * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGNOCOMP_FBR = BBRR2_FED_UGNOCOMP_FBR * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGNOCOMP_DFR = BBRR2_FED_UGNOCOMP_DFR * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGNOCOMP_NOPROG = BBRR2_FED_UGNOCOMP_NOPROG * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGNOCOMP_MAKEPROG = BBRR2_FED_UGNOCOMP_MAKEPROG * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGNOCOMP_PAIDINFULL = BBRR2_FED_UGNOCOMP_PAIDINFULL * BBRR2_FED_UG_N,
                        NUM_BBRR2_FED_UGNOCOMP_DISCHARGE = BBRR2_FED_UGNOCOMP_DISCHARGE * BBRR2_FED_UG_N
          )


debt_var <- csc_data %>% 
    select(all_of(bas), all_of(debt_variables)
           ) %>%
    mutate(DEPplusPARENT_DEBT_MDN = DEP_DEBT_MDN + PLUS_DEBT_INST_MD,
           DEPplusPARENTPELL_DEBT_MDN = DEP_DEBT_MDN + PLUS_DEBT_INST_PELL_MD)

# GCETU_rate
# UGLOAN2yr
# UGCOMPloan2yrs
# UGNOCOMPloan2yrs
# debt_var
###############################

# dGCETU_rate <- get_description(GCETU_rate %>% select(-all_of(bas), -onehundred))
# dUGLOAN2yr <- get_description(UGLOAN2yr %>% select(-all_of(bas), -onehundred))
# dUGCOMPloan2yrs <- get_description(UGCOMPloan2yrs %>% select(-all_of(bas), -onehundred))
# dUGNOCOMPloan2yrs <- get_description(UGNOCOMPloan2yrs %>% select(-all_of(bas), -onehundred))
# ddebt_var <- get_description(debt_var %>% select(-all_of(bas)))

# dGCETU_rate %>% 
#     mutate(median = median * 100, mean = mean * 100, Q1 = Q1 * 100, Q3 = Q3 * 100) %>%
#     view()
# dUGLOAN2yr %>% view()
# dUGCOMPloan2yrs %>% view()
# dUGNOCOMPloan2yrs %>% view()
# ddebt_var %>% view()
# rbind(dGCETU_rate, dUGLOAN2yr, dUGCOMPloan2yrs, dUGNOCOMPloan2yrs, ddebt_var) %>% view()

################################